# Bienvenidos

Esto es un notebook. Podemos escribir en lenguaje Markdown, el cual nos permite:
* Listas
* Escribir en **negrita** y *cursiva*
* Más información aquí: [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)


### PREGUNTAD!!

Sobretodo si os perdeis, no lleguemos a casos donde no sepais que estamos haciendo.

![Imagen no cargada. Edita y borra la @ ](https://img.buzzfeed.com/buzzfeed-static/static/2014-10/26/6/enhanced/webdr08/longform-original-14836-1414320930-10.jpg )

# Introducción

![ ](diagrama_resumen.png )

# Bibliografía 

Sobre **estadística**: [Practical Statistics for Data Scientists: 50 Essential Concepts](https://www.amazon.com/Practical-Statistics-Data-Scientists-Essential/dp/1491952962/ref=sr_1_3?ie=UTF8&qid=1518719786)


Sobre **R**: [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1491910399/ref=sr_1_1?ie=UTF8&qid=1518791084) Este libro es bastante completo, abarca mucho temario que no veremos por falta de tiempo.
                    


## Estadística vs Machine Learning


Más información aquí: [Markdown-Cheatsheet](https://www.reddit.com/r/MachineLearningLounge/comments/9soaw4/let_me_fix_that_for_you/)


* Estadística: Trata de entender las variables y su relación entre ellas. Las estadísitcas te ayudan a entender como es tu población de datos.

* Machine Learning: Trata de hacer predicciones, crear modelos que, a partir de una población limitada puedan **generalizar** y aprender como se comportarán los datos.



# Introducción a R

R es un lenguaje de programación orientado a la estadística.

Algo parecido a SPSS o Matlab.

Es código abierto y se entrega bajo licencia GPL (versión 2 o posterior). Además existen multitud de paquetes que complementan su funcionalidad.

## Asignaciones

Podemos usar <- o el símbolo = para asignar un valor a una variable

In [1]:
a <- 10

In [6]:
a

[1] 10

In [3]:
b = 2

In [7]:
b

[1] 2

In [5]:
print ("Hola mundo")

[1] "Hola mundo"


## Operaciones

In [9]:
print ("suma:")
a+b #Suma
print ("potencia:")
a^b #potencia
print ("módulo:")
a %% b #módulo
print ("división:")
a / b #División
print ("resta:")
a - b #Resta


[1] "suma:"


[1] 12

[1] "potencia:"


[1] 100

[1] "módulo:"


[1] 0

[1] "división:"


[1] 5

[1] "resta:"


[1] 8

## Funciones básicas

Las funciones 
 * siempre acaban en ()
 * pueden recibir un número variable de parámetros
 * pueden existir parámetros por defecto

Ver las variables en memoria, función ls()

In [10]:
ls()

[1] "a" "b"

Ver el tipo de variable, función typeof(x):

In [11]:
typeof(a)

[1] "double"

# Tipos de datos

## double

In [12]:
a<- 2018
a
typeof(a)

[1] 2018

[1] "double"

In [13]:
b <- exp(1)
b
typeof(b)

[1] 2.718282

[1] "double"

In [14]:
?exp

## integer

In [15]:
ai <- as.integer(3.789)
ai
typeof(ai)

[1] 3

[1] "integer"

## Diferencias entre  integer y double

El número más grande que podemos representar es diferente:

In [16]:
.Machine$integer.max
.Machine$double.xmax

[1] 2147483647

[1] 1.797693e+308

El tamaño que ocupan en memoria es:

In [17]:
object.size(ai)
object.size(b)

56 bytes

56 bytes

## character

In [18]:
s1 <- "Discovery"
s1
typeof(s1)

[1] "Discovery"

[1] "character"

Las cadenas de texto se pueden concatenar usando la función paste(x,y,z...)

In [19]:
?paste

In [20]:
paste(s1,"Lorca","tardigrado",sep="---|||---")

[1] "Discovery---|||---Lorca---|||---tardigrado"

## Logical

In [21]:
b1 <- TRUE
b2 <- T
b3 <- FALSE
paste("El valor de b1 es",b1)
paste("El valor de b2 es",b2)
paste("El valor de b3 es",b3)

[1] "El valor de b1 es TRUE"

[1] "El valor de b2 es TRUE"

[1] "El valor de b3 es FALSE"

In [22]:
print(paste("b1 AND b3:",b1 & b3))
print(paste("b1 OR  b3:",b1 | b3))
print(paste("b1 XOR b3:",xor(b1 ,b3)))
print(paste("   NOT b1:",!b1))

[1] "b1 AND b3: FALSE"
[1] "b1 OR  b3: TRUE"
[1] "b1 XOR b3: TRUE"
[1] "   NOT b1: FALSE"


## Vectores

Los vectores se crean con la función c(), todos los elementos de un vector son del mimo tipo. Es decir, no se podrían mezclar caracteres y double.

En python:

   a = [1,2,3,40]
   
En R:

   a = c(1,2,3,40)

In [24]:
alturas<-c(1.80,1.60,1.50,1.90,1.75,1.63,1.65)
alturas
print(paste("alturas es una variable de tipo:",typeof(alturas)))

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65

[1] "alturas es una variable de tipo: double"


In [25]:
print("Podemos ver la estructura de un objeto con la función str():")
str(alturas)

[1] "Podemos ver la estructura de un objeto con la función str():"
 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [26]:
otroVector <- c("uno",2.0,"tres","14.0")
otroVector
print(paste("otroVector es una variable de tipo:",typeof(otroVector)))

[1] "uno"  "2"    "tres" "14.0"

[1] "otroVector es una variable de tipo: character"


In [27]:
str(otroVector)

 chr [1:4] "uno" "2" "tres" "14.0"


### Acceso a elementos

In [28]:
print(paste("El valor del tercer elemento es:",alturas[3]))

[1] "El valor del tercer elemento es: 1.5"


**¡¡En R los arrays empiezan en 1!!**
![Imagen no cargada. Edita y borra la @ ](https://i.redd.it/iwnqgrrbls5z.png  )

Podemos dar nombres a cada elemento

In [29]:
myVector <- c(nombre="Philip",apellido="García",teléfono=600100100)

In [30]:
myVector

nombre    apellido    teléfono 
   "Philip"    "García" "600100100"

In [31]:
myVector["nombre"]

nombre 
"Philip"

In [32]:
myVector[2]

apellido 
"García"

In [33]:
myVector["teléfono"]

teléfono 
"600100100"

In [34]:
#Los nombres de una variable se pueden ver con la función names()
names(myVector)

[1] "nombre"   "apellido" "teléfono"

In [35]:
names(myVector) <- c("nombre_actualizado","apellido_actualizado", "telefono_actualizado")

In [36]:
myVector

nombre_actualizado apellido_actualizado telefono_actualizado 
            "Philip"             "García"          "600100100"

### Operaciones con vectores

Al operar contra una variable se aplica esa operación a todos los elementos del vector

In [37]:
metro2pie <- 3.28084
alturasEnPies <- alturas*metro2pie
alturasEnPies

[1] 5.905512 5.249344 4.921260 6.233596 5.741470 5.347769 5.413386

In [38]:
alturas

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65

Si se opera con dos vectores de la misma longitud se aplica elemento a elemento.

In [39]:
alturaDeLosZapatos<-c(2,0,1,3,5,7,0)/100
alturaReal<-alturas-alturaDeLosZapatos
alturaReal

[1] 1.78 1.60 1.49 1.87 1.70 1.56 1.65

Se puede operar con vectores de tamaños diferentes, en este caso el vector más pequeño se replica

In [40]:
alturas*c(1,0)

Warning message in alturas * c(1, 0):
“longer object length is not a multiple of shorter object length”


[1] 1.80 0.00 1.50 0.00 1.75 0.00 1.65

Concatenar vectores

In [41]:
c(alturas,2,1.8,17)

[1]  1.80  1.60  1.50  1.90  1.75  1.63  1.65  2.00  1.80 17.00

Longitud de un vector se obtiene con la función length()

In [42]:
length(alturas)

[1] 7

La estructura de la variable se puede ver con la función str()

In [43]:
str(alturas)

 num [1:7] 1.8 1.6 1.5 1.9 1.75 1.63 1.65


In [44]:
alturas[18]<-1.9

In [45]:
alturas

[1] 1.80 1.60 1.50 1.90 1.75 1.63 1.65   NA   NA   NA   NA   NA   NA   NA   NA
[16]   NA   NA 1.90

In [46]:
length(alturas)

[1] 18

## Listas

Las listas se pueden considerar como vectores que pueden almacenar cualquier tipo de dato.

In [47]:
c(1,3,"catorce","panama")

[1] "1"       "3"       "catorce" "panama"

In [48]:
myList<-list(1,3,"catorce","panama")
str(myList)

List of 4
 $ : num 1
 $ : num 3
 $ : chr "catorce"
 $ : chr "panama"


In [49]:
myList

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] "catorce"

[[4]]
[1] "panama"

Podemos asignar un nombre a cada valor

In [50]:
datosPersonales<-list(nombre="Philip",
                   apellido="García",
                   teléfono=600100100)
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

### Acceso a elementos

Podemos acceder a los distintos elementos utilizando su índice o nombre:

In [51]:
datosPersonales[[1]]

[1] "Philip"

In [52]:
datosPersonales[["nombre"]]

[1] "Philip"

In [53]:
datosPersonales$nombre

[1] "Philip"

In [54]:
is.null(datosPersonales[["direccion"]])

[1] TRUE

In [55]:
datosPersonales[["direccion"]]

NULL

In [56]:
names(datosPersonales)

[1] "nombre"   "apellido" "teléfono"

In [57]:
datosPersonales[["direccion"]]<-list(ciudad="Madrid",calle="Desengaño",numero=21)
datosPersonales[["direccion"]]

$ciudad
[1] "Madrid"

$calle
[1] "Desengaño"

$numero
[1] 21

In [58]:
datosPersonales

$nombre
[1] "Philip"

$apellido
[1] "García"

$teléfono
[1] 600100100

$direccion
$direccion$ciudad
[1] "Madrid"

$direccion$calle
[1] "Desengaño"

$direccion$numero
[1] 21

In [59]:
datosPersonales[["direccion"]]$calle

[1] "Desengaño"

In [60]:
datosPersonales$direccion$calle

[1] "Desengaño"

In [61]:
str(datosPersonales)

List of 4
 $ nombre   : chr "Philip"
 $ apellido : chr "García"
 $ teléfono : num 6e+08
 $ direccion:List of 3
  ..$ ciudad: chr "Madrid"
  ..$ calle : chr "Desengaño"
  ..$ numero: num 21


In [62]:
print(paste("La longitud total de la lista es",length(datosPersonales)))

[1] "La longitud total de la lista es 4"


## Factores

Útiles cuando trabajamos con variables categóricas. Ej: Población de origen, colores, sabores

In [63]:
saboresDePlatos<-c("Dulce","Salado","Ácido","Amargo","Umami","Dulce","Salado","Ácido","Umami","Umami","Salado")
saboresDePlatosFactor<-factor(saboresDePlatos)

summary(saboresDePlatos)
summary(saboresDePlatosFactor)

   Length     Class      Mode 
       11 character character 

Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3

In [64]:
saboresDePlatos
saboresDePlatosFactor

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

[1] Dulce  Salado Ácido  Amargo Umami  Dulce  Salado Ácido  Umami  Umami 
[11] Salado
Levels: Ácido Amargo Dulce Salado Umami

In [65]:
str(saboresDePlatos)

 chr [1:11] "Dulce" "Salado" "Ácido" "Amargo" "Umami" "Dulce" "Salado" ...


In [66]:
str(saboresDePlatosFactor)

 Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


In [67]:
saboresDePlatosFactor

[1] Dulce  Salado Ácido  Amargo Umami  Dulce  Salado Ácido  Umami  Umami 
[11] Salado
Levels: Ácido Amargo Dulce Salado Umami

In [68]:
print("Los factores internamente se gestionan como enteros")
as.numeric(saboresDePlatosFactor)

[1] "Los factores internamente se gestionan como enteros"


[1] 3 4 1 2 5 3 4 1 5 5 4

In [69]:
paste("sabor:",levels(saboresDePlatosFactor))

[1] "sabor: Ácido"  "sabor: Amargo" "sabor: Dulce"  "sabor: Salado"
[5] "sabor: Umami"

In [70]:
print(paste("Podemos ver los niveles con el comando levels:",
            paste(levels(saboresDePlatosFactor),collapse=",")))

[1] "Podemos ver los niveles con el comando levels: Ácido,Amargo,Dulce,Salado,Umami"


In [75]:
factorNumeros<-factor(c(1,0,0,1,0,1),labels=c("NO","SI"))
factorNumeros

[1] SI NO NO SI NO SI
Levels: NO SI

In [76]:
summary(factorNumeros)

NO SI 
 3  3

In [74]:
factor(c(10,5,5,0,5,0),labels=c("BAJO","MEDIO","ALTO"))

[1] ALTO  MEDIO MEDIO BAJO  MEDIO BAJO 
Levels: BAJO MEDIO ALTO

# Matrices

Podemos crear matrices con la función matrix. Como parámetros de entrada recibe un vector y el número de columnas (*ncol*) o filas (nrow). Un parámetro opcional (*byrow*) indica si la matriz se va a rellenar por filas o por columnas (valor por defecto)

In [77]:
1:12

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [78]:
m1<-matrix(c(1:12),ncol=3)
m1

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [79]:
?matrix

In [84]:
m2<-matrix(c(1:12),ncol=3,byrow=T)
m2

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

La dimensión del array se puede ver con la función *dim()* o con *str()*

In [80]:
dim(m1)

[1] 4 3

In [81]:
length(m1)

[1] 12

In [85]:
str(m2)

 int [1:4, 1:3] 1 4 7 10 2 5 8 11 3 6 ...


### Acceso

El acceso se realiza igual que los vectores, pero aquí tenemos dos dimensiones.

In [86]:
m1[1,3]

[1] 9

También podemos dar nombres a las filas y columnas para luego poder acceder utilizando el nombre

In [87]:
?paste0

In [88]:
paste0("row",1:4)

[1] "row1" "row2" "row3" "row4"

In [89]:
colnames(m1)<-paste0("col",1:3)
rownames(m1)<-paste0("row",1:4)
m1

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

In [92]:
paste("El valor de 'row1' y 'col3' es:",m1["row1","col3"])


[1] "El valor de 'row1' y 'col3' es: 9"

Las funciones *colnames* y *rownames* 

In [93]:
rownames(m1)

[1] "row1" "row2" "row3" "row4"

### Operaciones con matrices 
#### Álgebra lineal básica

In [94]:
m1

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

Transpuesta

In [95]:
t(m1)

row1 row2 row3 row4
col1 1     2    3    4  
col2 5     6    7    8  
col3 9    10   11   12

Suma de constante

In [96]:
m1+10

col1 col2 col3
row1 11   15   19  
row2 12   16   20  
row3 13   17   21  
row4 14   18   22

Suma de matrices

In [97]:
m1+m2

col1 col2 col3
row1  2    7   12  
row2  6   11   16  
row3 10   15   20  
row4 14   19   24

In [98]:
m1
m2

col1 col2 col3
row1 1    5     9  
row2 2    6    10  
row3 3    7    11  
row4 4    8    12

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

Multiplicación de matrices

In [99]:
m1 %*% matrix(rep(1,12),nrow=3)

[,1] [,2] [,3] [,4]
row1 15   15   15   15  
row2 18   18   18   18  
row3 21   21   21   21  
row4 24   24   24   24

In [100]:
rep("a",5)

[1] "a" "a" "a" "a" "a"

Submatrices

In [101]:
m1[2:4,2:3]

col2 col3
row2 6    10  
row3 7    11  
row4 8    12

In [102]:
m1[c(3,2,4),2:3]

col2 col3
row3 7    11  
row2 6    10  
row4 8    12

# Tablas

Se utilizan para estudios de frecuencia. Cuentan el número de veces que ha ocurrido algo.

In [103]:
saboresDePlatos

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

In [104]:
tblSabores<-table(saboresDePlatos)
tblSabores

saboresDePlatos
 Ácido Amargo  Dulce Salado  Umami 
     2      1      2      3      3 

In [105]:
names(tblSabores)

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [106]:
str(tblSabores)

 'table' int [1:5(1d)] 2 1 2 3 3
 - attr(*, "dimnames")=List of 1
  ..$ saboresDePlatos: chr [1:5] "Ácido" "Amargo" "Dulce" "Salado" ...


Los atributos son una lista de propiedades asociadas a un objeto en R

In [107]:
attributes(tblSabores)

$dim
[1] 5

$dimnames
$dimnames$saboresDePlatos
[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami" 


$class
[1] "table"

In [108]:
class(tblSabores)

[1] "table"

In [109]:
attributes(tblSabores)$dimnames$saboresDePlatos 

[1] "Ácido"  "Amargo" "Dulce"  "Salado" "Umami"

In [110]:
color  <- c("marrón","negro","blanco","negro","blanco","negro","negro","marrón","marrón","marrón")
animal <- c("gato","gato","perro","gato","gato","perro","perro","perro","gato","gato")

tbl_animal<-table(animal,color)
tbl_animal

       color
animal  blanco marrón negro
  gato       1      3     2
  perro      1      1     2

In [111]:
str(tbl_animal)

 'table' int [1:2, 1:3] 1 1 3 1 2 2
 - attr(*, "dimnames")=List of 2
  ..$ animal: chr [1:2] "gato" "perro"
  ..$ color : chr [1:3] "blanco" "marrón" "negro"


In [112]:
attributes(tbl_animal)$dimnames

$animal
[1] "gato"  "perro"

$color
[1] "blanco" "marrón" "negro"

In [113]:
attributes(tbl_animal)

$dim
[1] 2 3

$dimnames
$dimnames$animal
[1] "gato"  "perro"

$dimnames$color
[1] "blanco" "marrón" "negro" 


$class
[1] "table"

## Miniresumen parcial

Vector

In [114]:
vecto_pesos <- c(5,7,8,9,10)
vecto_pesos[2:3]

[1] 7 8

Listas

In [115]:
lista_medidas <- list(altura=1.5, ancho=1, peso = 3, unidades_peso="Kg", unidades_medida="m", 
                      fabricacion=list(numeroserie="A1238656", origen="Zamora"))
lista_medidas

$altura
[1] 1.5

$ancho
[1] 1

$peso
[1] 3

$unidades_peso
[1] "Kg"

$unidades_medida
[1] "m"

$fabricacion
$fabricacion$numeroserie
[1] "A1238656"

$fabricacion$origen
[1] "Zamora"

In [116]:
lista_medidas[["altura"]]

[1] 1.5

## Data Frame

Conjunto de vectores de la misma longitud. Cada vector puede ser de un tipo diferente.

In [117]:
plt <- c("Bollo","Palomitas","Limón","Ginebra","Noodles","Caramelo","Patatas fritas","Naranja","Ternera","Cerdo","Sopa")
cal <-c(150,200,10,20,200,5,500,15,450,460,30)

In [118]:
idx<- 5 
paste("Elemento",idx,":",plt[idx],"-",cal[idx],"cal")

[1] "Elemento 5 : Noodles - 200 cal"

In [119]:
comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = F)
comidas
str(comidas)

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

'data.frame':	11 obs. of  3 variables:
 $ plato   : chr  "Bollo" "Palomitas" "Limón" "Ginebra" ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : chr  "Dulce" "Salado" "Ácido" "Amargo" ...


### Acceso a elementos de un data frame

Acceso por filas:

In [120]:
comidas[2:3,]

plato     calorias sabor 
2 Palomitas 200      Salado
3 Limón      10      Ácido

In [121]:
comidas[c(-1,-3,-5,-10,-11),]

plato          calorias sabor 
2 Palomitas      200      Salado
4 Ginebra         20      Amargo
6 Caramelo         5      Dulce 
7 Patatas fritas 500      Salado
8 Naranja         15      Ácido 
9 Ternera        450      Umami

Acceso por columnas:

In [122]:
comidas[,c("plato","calorias")]

plato          calorias
1  Bollo          150     
2  Palomitas      200     
3  Limón           10     
4  Ginebra         20     
5  Noodles        200     
6  Caramelo         5     
7  Patatas fritas 500     
8  Naranja         15     
9  Ternera        450     
10 Cerdo          460     
11 Sopa            30

Se puede usar el símbolo **$** para acceder a una columna.  
Las siguientes dos llamadas son equivalentes:

In [123]:
comidas$plato

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [124]:
comidas[,"plato"]

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [125]:
comidas[,1]

[1] "Bollo"          "Palomitas"      "Limón"          "Ginebra"       
 [5] "Noodles"        "Caramelo"       "Patatas fritas" "Naranja"       
 [9] "Ternera"        "Cerdo"          "Sopa"

In [126]:
comidas[,c(-1,-2)]

[1] "Dulce"  "Salado" "Ácido"  "Amargo" "Umami"  "Dulce"  "Salado" "Ácido" 
 [9] "Umami"  "Umami"  "Salado"

In [127]:
comidas$plato[2:3]

[1] "Palomitas" "Limón"

In [128]:
comidas[2:3,"plato"]

[1] "Palomitas" "Limón"

In [129]:
colnames(comidas)

[1] "plato"    "calorias" "sabor"

Número de filas que tiene un dataframe:

In [130]:
nrow(comidas)

[1] 11

También podemos dar nombres a las filas

In [131]:
rownames(comidas)<-paste0("comida",1:nrow(comidas))
comidas

plato          calorias sabor 
comida1  Bollo          150      Dulce 
comida2  Palomitas      200      Salado
comida3  Limón           10      Ácido 
comida4  Ginebra         20      Amargo
comida5  Noodles        200      Umami 
comida6  Caramelo         5      Dulce 
comida7  Patatas fritas 500      Salado
comida8  Naranja         15      Ácido 
comida9  Ternera        450      Umami 
comida10 Cerdo          460      Umami 
comida11 Sopa            30      Salado

In [132]:
comidas["comida5","calorias"]

[1] 200

In [133]:
comidas[5,"calorias"]

[1] 200

In [134]:
comidas[c(4,2),c(3,2,1)]

sabor  calorias plato    
comida4 Amargo  20      Ginebra  
comida2 Salado 200      Palomitas

El nombre de las columnas y de las filas se puede obtener y modificar con las funciones **colnames()** y **rownames()**.

In [135]:
colnames(comidas)
rownames(comidas)

[1] "plato"    "calorias" "sabor"

[1] "comida1"  "comida2"  "comida3"  "comida4"  "comida5"  "comida6" 
 [7] "comida7"  "comida8"  "comida9"  "comida10" "comida11"

### Dataset con variable categoricas 

In [136]:
comidas<-data.frame(plato=plt, calorias=cal, sabor=saboresDePlatos, stringsAsFactors = T)
comidas
str(comidas)

plato          calorias sabor 
1  Bollo          150      Dulce 
2  Palomitas      200      Salado
3  Limón           10      Ácido 
4  Ginebra         20      Amargo
5  Noodles        200      Umami 
6  Caramelo         5      Dulce 
7  Patatas fritas 500      Salado
8  Naranja         15      Ácido 
9  Ternera        450      Umami 
10 Cerdo          460      Umami 
11 Sopa            30      Salado

'data.frame':	11 obs. of  3 variables:
 $ plato   : Factor w/ 11 levels "Bollo","Caramelo",..: 1 8 5 4 7 2 9 6 11 3 ...
 $ calorias: num  150 200 10 20 200 5 500 15 450 460 ...
 $ sabor   : Factor w/ 5 levels "Ácido","Amargo",..: 3 4 1 2 5 3 4 1 5 5 ...


## Arrays 3D

Se pueden crear arrays N-dimensionales con la función array

In [137]:
arr<-array(1:12,dim = c(3,2,2))
arr

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

El acceso a elementos es similar al de las matrices

In [138]:
arr[1,2,1]

[1] 4

In [139]:
arr[1,,]

[,1] [,2]
[1,] 1     7  
[2,] 4    10

In [140]:
arr[2,,]

[,1] [,2]
[1,] 2     8  
[2,] 5    11

In [141]:
arr[3,,]

[,1] [,2]
[1,] 3     9  
[2,] 6    12

In [142]:
arr[4,,]

ERROR: Error in arr[4, , ]: subscript out of bounds


In [143]:
arr[,2,]

[,1] [,2]
[1,] 4    10  
[2,] 5    11  
[3,] 6    12

## Fechas

Existen dos objetos para almacenar fechas en R.

* Posixct es recubrimiento sobre un timestamp en segundos.
* Posixlt es una lista de objetos que contiene la información de la fecha

In [144]:
d1<-as.POSIXct("2018-10-5 15:40")
d2<-as.POSIXct("5/10/2018 17:33",format="%m/%d/%Y")

d1
d2

[1] "2018-10-05 15:40:00 UTC"

[1] "2018-05-10 UTC"

In [145]:
str(d1)

 POSIXct[1:1], format: "2018-10-05 15:40:00"


In [146]:
class(d1)

[1] "POSIXct" "POSIXt"

In [147]:
unclass(d1)

[1] 1538754000
attr(,"tzone")
[1] ""

In [148]:
d1+60*60*24


[1] "2018-10-06 15:40:00 UTC"

In [149]:
d3<-as.POSIXlt("2018-4-5")
d3

[1] "2018-04-05 UTC"

In [150]:
d3

[1] "2018-04-05 UTC"

In [151]:
d3$mday<-6

In [152]:
d3

[1] "2018-04-06 UTC"

In [153]:
str(d3)

 POSIXlt[1:1], format: "2018-04-06"


In [154]:
c(as.POSIXct("2018-01-01"),as.POSIXct("2018-01-02"),as.POSIXct("2018-01-03"))

[1] "2018-01-01 UTC" "2018-01-02 UTC" "2018-01-03 UTC"

In [155]:
df<-data.frame(fecha=c(as.POSIXlt("2018-01-01"),as.POSIXlt("2018-01-02"),as.POSIXlt("2018-01-03")))
str(df)


'data.frame':	3 obs. of  1 variable:
 $ fecha: POSIXct, format: "2018-01-01" "2018-01-02" ...


## Valores no disponibles / Missing Values

Son valores para los cuales no tenemos ninguna medida, se representan con un NA.

Pertenecen a valores perdidos que no se han podido recuperar, errores de medida, perdidas de datos, etc..

En R los detectamos con:

is.na(x)
y podemos reemplazar su valor con la media, moda, mediana, etc...

o simplemente eliminarlos: na.omit(x)

Si estamos trabajando con series temporales es posible que queramos hacer una interpolación de los valores perdidos:

zoo::na.approx(x)

In [156]:
NA

[1] NA

In [157]:
data<-c(1,3,NA,6)
data

[1]  1  3 NA  6

In [158]:
is.na(data)

[1] FALSE FALSE  TRUE FALSE

In [159]:
na.omit(data)

[1] 1 3 6
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"

In [163]:
paste("El número de elementos con NA:",length(data[is.na(data)]))

[1] "El número de elementos con NA: 1"

In [164]:
paste("El número de elementos que NO son NA:",length(data[!is.na(data)]))

[1] "El número de elementos que NO son NA: 3"

In [166]:
data[1]<-10
data

[1] 10  3 NA  6

In [167]:
data[is.na(data)] <- 28
data

[1] 10  3 28  6

## Ejemplo datos reales


#### Dataset coches

Partimos del dataset de seguro de automóviles que podemos descargar de:

https://archive.ics.uci.edu/ml/datasets/Automobile


In [168]:
autos<-read.csv("./data//imports-85.data", col.names = c("risk", "normalized_losses", 
                                                         "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"))

In [169]:
str(autos)

'data.frame':	204 obs. of  26 variables:
 $ risk             : int  3 1 2 2 2 1 1 1 0 2 ...
 $ normalized_losses: Factor w/ 52 levels "?","101","102",..: 1 1 29 29 1 27 1 27 1 33 ...
 $ make             : Factor w/ 22 levels "alfa-romero",..: 1 1 2 2 2 2 2 2 2 3 ...
 $ fuel_type        : Factor w/ 2 levels "diesel","gas": 2 2 2 2 2 2 2 2 2 2 ...
 $ aspiration       : Factor w/ 2 levels "std","turbo": 1 1 1 1 1 1 1 2 2 1 ...
 $ num_doors        : Factor w/ 3 levels "?","four","two": 3 3 2 2 3 2 2 2 3 3 ...
 $ body_style       : Factor w/ 5 levels "convertible",..: 1 3 4 4 4 4 5 4 3 4 ...
 $ drive_wheels     : Factor w/ 3 levels "4wd","fwd","rwd": 3 3 2 1 2 2 2 2 1 3 ...
 $ engine_location  : Factor w/ 2 levels "front","rear": 1 1 1 1 1 1 1 1 1 1 ...
 $ wheel_base       : num  88.6 94.5 99.8 99.4 99.8 ...
 $ length           : num  169 171 177 177 177 ...
 $ width            : num  64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 64.8 ...
 $ height           : num  48.8 52.4 54.3 54.3 53.1 5

In [170]:
head(autos)

risk normalized_losses make        fuel_type aspiration num_doors body_style 
1 3    ?                 alfa-romero gas       std        two       convertible
2 1    ?                 alfa-romero gas       std        two       hatchback  
3 2    164               audi        gas       std        four      sedan      
4 2    164               audi        gas       std        four      sedan      
5 2    ?                 audi        gas       std        two       sedan      
6 1    158               audi        gas       std        four      sedan      
  drive_wheels engine_location wheel_base ⋯ engine_size fuel_system bore stroke
1 rwd          front            88.6      ⋯ 130         mpfi        3.47 2.68  
2 rwd          front            94.5      ⋯ 152         mpfi        2.68 3.47  
3 fwd          front            99.8      ⋯ 109         mpfi        3.19 3.40  
4 4wd          front            99.4      ⋯ 136         mpfi        3.19 3.40  
5 fwd          front            99.8      ⋯ 136         mpfi        3.19 3.40  
6 fwd          front           105.8      ⋯ 136         mpfi        3.19 3.40  
  compression_ratio horsepower peak_rpm city_mpg highway_mpg price
1  9.0              111        5000     21       27          16500
2  9.0              154        5000     19       26          16500
3 10.0              102        5500     24       30          13950
4  8.0              115        5500     18       22          17450
5  8.5              110        5500     19       25          15250
6  8.5              110        5500     19       25          17710

Nos quedamos solo con las columnas: "price","horsepower","body_style","risk"

In [171]:
head(autos[,c("price","horsepower","body_style","risk")])

price horsepower body_style  risk
1 16500 111        convertible 3   
2 16500 154        hatchback   1   
3 13950 102        sedan       2   
4 17450 115        sedan       2   
5 15250 110        sedan       2   
6 17710 110        sedan       1

In [172]:
autos$fuel_type<-NULL
head(autos)

risk normalized_losses make        aspiration num_doors body_style 
1 3    ?                 alfa-romero std        two       convertible
2 1    ?                 alfa-romero std        two       hatchback  
3 2    164               audi        std        four      sedan      
4 2    164               audi        std        four      sedan      
5 2    ?                 audi        std        two       sedan      
6 1    158               audi        std        four      sedan      
  drive_wheels engine_location wheel_base length ⋯ engine_size fuel_system bore
1 rwd          front            88.6      168.8  ⋯ 130         mpfi        3.47
2 rwd          front            94.5      171.2  ⋯ 152         mpfi        2.68
3 fwd          front            99.8      176.6  ⋯ 109         mpfi        3.19
4 4wd          front            99.4      176.6  ⋯ 136         mpfi        3.19
5 fwd          front            99.8      177.3  ⋯ 136         mpfi        3.19
6 fwd          front           105.8      192.7  ⋯ 136         mpfi        3.19
  stroke compression_ratio horsepower peak_rpm city_mpg highway_mpg price
1 2.68    9.0              111        5000     21       27          16500
2 3.47    9.0              154        5000     19       26          16500
3 3.40   10.0              102        5500     24       30          13950
4 3.40    8.0              115        5500     18       22          17450
5 3.40    8.5              110        5500     19       25          15250
6 3.40    8.5              110        5500     19       25          17710

In [173]:
autos<-autos[,c("price","horsepower","body_style","risk")]
head(autos)

price horsepower body_style  risk
1 16500 111        convertible 3   
2 16500 154        hatchback   1   
3 13950 102        sedan       2   
4 17450 115        sedan       2   
5 15250 110        sedan       2   
6 17710 110        sedan       1

In [174]:
summary(autos)

     price       horsepower        body_style      risk        
 ?      :  4   68     : 19   convertible: 5   Min.   :-2.0000  
 13499  :  2   70     : 11   hardtop    : 8   1st Qu.: 0.0000  
 16500  :  2   69     : 10   hatchback  :70   Median : 1.0000  
 18150  :  2   116    :  9   sedan      :96   Mean   : 0.8235  
 5572   :  2   110    :  8   wagon      :25   3rd Qu.: 2.0000  
 6229   :  2   95     :  7                    Max.   : 3.0000  
 (Other):190   (Other):140                                     

In [175]:
str(autos)

'data.frame':	204 obs. of  4 variables:
 $ price     : Factor w/ 186 levels "?","10198","10245",..: 51 51 37 62 42 64 72 82 1 50 ...
 $ horsepower: Factor w/ 60 levels "?","100","101",..: 7 22 4 10 6 6 6 17 25 3 ...
 $ body_style: Factor w/ 5 levels "convertible",..: 1 3 4 4 4 4 5 4 3 4 ...
 $ risk      : int  3 1 2 2 2 1 1 1 0 2 ...


En este CSV cuando existe un valor desconocido lo han indicado con el caracter '?'. Por ese motivo la columna 'price' y 'horsepower' es factor en lugar de numeric.
Tenemos que indicarle a R que son NA:

In [179]:
autos$price[autos$price=='?']<-NA
autos[autos$horsepower=='?','horsepower']<-NA
autos

price horsepower body_style  risk
1   16500 111        convertible  3  
2   16500 154        hatchback    1  
3   13950 102        sedan        2  
4   17450 115        sedan        2  
5   15250 110        sedan        2  
6   17710 110        sedan        1  
7   18920 110        wagon        1  
8   23875 140        sedan        1  
9   NA    160        hatchback    0  
10  16430 101        sedan        2  
11  16925 101        sedan        0  
12  20970 121        sedan        0  
13  21105 121        sedan        0  
14  24565 121        sedan        1  
15  30760 182        sedan        0  
16  41315 182        sedan        0  
17  36880 182        sedan        0  
18  5151  48         hatchback    2  
19  6295  70         hatchback    1  
20  6575  70         sedan        0  
21  5572  68         hatchback    1  
22  6377  68         hatchback    1  
23  7957  102        hatchback    1  
24  6229  68         hatchback    1  
25  6692  68         sedan        1  
26  7609  68         sedan        1  
27  8558  102        sedan        1  
28  8921  88         wagon       -1  
29  12964 145        hatchback    3  
30  6479  58         hatchback    2  
⋮   ⋮     ⋮          ⋮           ⋮   
175 9988  92         hatchback   -1  
176 10898 92         sedan       -1  
177 11248 92         hatchback   -1  
178 16558 161        hatchback    3  
179 15998 161        hatchback    3  
180 15690 156        sedan       -1  
181 15750 156        wagon       -1  
182 7775  52         sedan        2  
183 7975  85         sedan        2  
184 7995  52         sedan        2  
185 8195  85         sedan        2  
186 8495  85         sedan        2  
187 9495  68         sedan        2  
188 9995  100        sedan        2  
189 11595 90         convertible  3  
190 9980  90         hatchback    3  
191 13295 110        sedan        0  
192 13845 68         sedan        0  
193 12290 88         wagon        0  
194 12940 114        sedan       -2  
195 13415 114        wagon       -1  
196 15985 114        sedan       -2  
197 16515 114        wagon       -1  
198 18420 162        sedan       -2  
199 18950 162        wagon       -1  
200 16845 114        sedan       -1  
201 19045 160        sedan       -1  
202 21485 134        sedan       -1  
203 22470 106        sedan       -1  
204 22625 114        sedan       -1

In [182]:
summary(autos)

     price       horsepower        body_style      risk        
 13499  :  2   68     : 19   convertible: 5   Min.   :-2.0000  
 16500  :  2   70     : 11   hardtop    : 8   1st Qu.: 0.0000  
 18150  :  2   69     : 10   hatchback  :70   Median : 1.0000  
 5572   :  2   116    :  9   sedan      :96   Mean   : 0.8235  
 6229   :  2   110    :  8   wagon      :25   3rd Qu.: 2.0000  
 (Other):190   (Other):145                    Max.   : 3.0000  
 NA's   :  4   NA's   :  2                                     

Tenemos que convertir el factor de 'price' y 'horsepower' en valores numéricos:

In [184]:
as.numeric(autos$horsepower)
#da el valor correspondiente al nivel. No vemos ningún 1 que es el que se corresponde al ?

[1]  7 22  4 10  6  6  6 17 25  3  3 13 13 13 30 30 30 36 46 46 44 44  4 44 44
 [26] 44  4 55 20 40 49 41 49 49 49 49 54 54 54 54  3  2 50 46 46 56 29 29 34 44
 [51] 44 44 44 44  3  3  3 16 52 52 52 52 43 52 12 47 14 14 14 14 23 23 31 31 28
 [76] 44 44 44  4 11 55 20 20 20 55 55 11 11 45 38 45 45 45 45 45 45 45 45 60 60
[101] 21 21 21 25 32 25 60 59 60 59 59 59 59 59 60 59 18 44  4 44 44 44 55 20 19
[126] 33 33 33 35 NA NA  6  6  6  6 25 25 45 48 48 51 51 58 51  7 51 58 51  7 42
[151] 42 42 42 42 42 46 46 39 39 46 46 46 46 46  8  8 11 11 11 11 11 11 57 48 57
[176] 57 57 26 26 24 24 37 53 37 53 53 44  2 56 56  6 44 55  9  9  9  9 27 27  9
[201] 25 15  5  9

In [188]:
#si tratamos con factores, primero convertimos a caracter y luego a número
autos$horsepower<-as.numeric(as.character(autos$horsepower))
autos$price<-as.numeric(as.character(autos$price))
summary(autos)

     price         horsepower          body_style      risk        
 Min.   : 5118   Min.   : 48.0   convertible: 5   Min.   :-2.0000  
 1st Qu.: 7775   1st Qu.: 70.0   hardtop    : 8   1st Qu.: 0.0000  
 Median :10270   Median : 95.0   hatchback  :70   Median : 1.0000  
 Mean   :13206   Mean   :104.2   sedan      :96   Mean   : 0.8235  
 3rd Qu.:16501   3rd Qu.:116.0   wagon      :25   3rd Qu.: 2.0000  
 Max.   :45400   Max.   :288.0                    Max.   : 3.0000  
 NA's   :4       NA's   :2                                         

In [189]:
summary(na.omit(autos))

     price         horsepower          body_style      risk        
 Min.   : 5118   Min.   : 48.0   convertible: 5   Min.   :-2.0000  
 1st Qu.: 7775   1st Qu.: 70.0   hardtop    : 8   1st Qu.: 0.0000  
 Median :10320   Median : 95.0   hatchback  :67   Median : 1.0000  
 Mean   :13242   Mean   :103.4   sedan      :94   Mean   : 0.8283  
 3rd Qu.:16502   3rd Qu.:116.0   wagon      :24   3rd Qu.: 2.0000  
 Max.   :45400   Max.   :262.0                    Max.   : 3.0000  

In [191]:
autos[is.na(autos$price),]

price horsepower body_style risk
9   NA    160        hatchback  0   
44  NA     70        sedan      1   
45  NA     70        sedan      0   
129 NA    288        hatchback  1

In [192]:
autos[is.na(autos$horsepower),]

price horsepower body_style risk
130 9295  NA         wagon      0   
131 9895  NA         hatchback  2

#### Dataset cancer esófago


Se realizó un estudio retrospectivo de casos y controles de 200 casos masculinos de cáncer de esófago y 778 controles poblacionales en Ille-et-Vilanine (Francia). Los logaritmos de los riesgos relativos de desarrollar la enfermedad aumentan linealmente con el consumo diario de alcohol y tabaco de manera independiente. El efecto combinado de ambos se ajusta con un modelo multiplicativo que se propone. Este modelo podría ser aplicable a otras situaciones. Explica la proporción de sexos y las diferencias urbanas / rurales observadas en Ille-er-Vilaine. 

http://www.math.umd.edu/~evs/s430.old/Data/ESOPH.dat

Columnas:
* agegp: grupo de edad
* alcgp: consumo de alcohol
* tobgp: consumo de tabaco
* ncases: número de casos de cancer
* ncontrol: población de control


In [193]:
dfcancer<-read.csv("data/ESOPH.dat",skip=43,sep = "")
head(dfcancer)

agegp alcgp     tobgp    ncases ncontrols
1 25-34 0-39g/day 0-9g/day 0      40       
2 25-34 0-39g/day 10-19    0      10       
3 25-34 0-39g/day 20-29    0       6       
4 25-34 0-39g/day 30+      0       5       
5 25-34 40-79     0-9g/day 0      27       
6 25-34 40-79     10-19    0       7

In [194]:
str(dfcancer)

'data.frame':	88 obs. of  5 variables:
 $ agegp    : Factor w/ 6 levels "25-34","35-44",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ alcgp    : Factor w/ 4 levels "0-39g/day","120+",..: 1 1 1 1 3 3 3 3 4 4 ...
 $ tobgp    : Factor w/ 4 levels "0-9g/day","10-19",..: 1 2 3 4 1 2 3 4 1 2 ...
 $ ncases   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ ncontrols: int  40 10 6 5 27 7 4 7 2 1 ...


In [195]:
unique(dfcancer$agegp)

[1] 25-34 35-44 45-54 55-64 65-74 75+  
Levels: 25-34 35-44 45-54 55-64 65-74 75+

In [196]:
ageVectors<-c(30,40,50,60,70,80)

In [197]:
as.numeric(dfcancer$agegp)

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3
[39] 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[77] 5 6 6 6 6 6 6 6 6 6 6 6

In [198]:
ageVectors[as.numeric(dfcancer$agegp)]

[1] 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 40 40 40 40 40 40 40 40 40 40
[26] 40 40 40 40 40 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 60 60 60 60
[51] 60 60 60 60 60 60 60 60 60 60 60 60 70 70 70 70 70 70 70 70 70 70 70 70 70
[76] 70 70 80 80 80 80 80 80 80 80 80 80 80

In [199]:
summary(dfcancer)

   agegp          alcgp         tobgp        ncases         ncontrols    
 25-34:15   0-39g/day:23   0-9g/day:24   Min.   : 0.000   Min.   : 1.00  
 35-44:15   120+     :21   10-19   :24   1st Qu.: 0.000   1st Qu.: 3.00  
 45-54:16   40-79    :23   20-29   :20   Median : 1.000   Median : 6.00  
 55-64:16   80-119   :21   30+     :20   Mean   : 2.273   Mean   :11.08  
 65-74:15                                3rd Qu.: 4.000   3rd Qu.:14.00  
 75+  :11                                Max.   :17.000   Max.   :60.00  

En ocasiones podemos convertir los factores en números. Com en este caso que sustituimos los rangos por su valor medio: