# 10. Funciones lineales

## Definición formal de una función

Una función relaciona cada elemento de un conjunto con exactamente un elemento de otro conjunto (puede ser el mismo conjunto).  
> f: X $\rightarrow$ Y



## Dominio, codominio e imagen

Hay nombres especiales para lo que puede entrar, y también lo que puede salir de una función:

* Lo que puede entrar en una función se llama el **dominio**.  
* Lo que es posible que salga de una función se llama el **codominio**.  
* Lo que en realidad sale de una función se llama **rango** o **imagen**  

<img src="Images/function-sets.gif" style="width: 200px;"/> 

## Funciones o transformaciones vectoriales

f: $\mathbb{R}$<sup>n</sup> $\rightarrow \mathbb{R}$<sup>m</sup>

Una **transformación vectorial** es una función que opera entre vectores.

Se suelen denotar por T mayúscula.




## Funciones o transformaciones lineales  

Dados $\mathbb{V}$ y $\mathbb{W}$, espacios vectoriales de $\mathbb{F}$.  
Supongamos que una función f: $\mathbb{V}$ $\longrightarrow$ $\mathbb{W}$ satisface dos propiedades:  
* Para cada vector v en V y cada escalar α en F, f (αv) = αf(v)  
* Por cada dos vectores u y v en V, f (u + v) = f (u) + f (v)  

Entonces llamamos a f **función lineal** o **transformación lineal** u **homomorfismo**.  

<span style="color:orange"> Ejemplo:  
¿La función f(x,y)=(x+y,3x) es una función lineal?  
</style>  
* <span style="color:orange">f(αx,αy)=(αx+αy,3αx)=α(x+y,3x)=α$\cdot$f(x,y)</style>  
* <span style="color:orange">f([x<sub>1</sub>,y<sub>1</sub>]+[x<sub>2</sub>,y<sub>2</sub>] = f([x<sub>1</sub>+x<sub>2</sub>,y<sub>1</sub>+y<sub>2</sub>]) = 
[x<sub>1</sub>+x<sub>2</sub>+y<sub>1</sub>+y<sub>2</sub>,3$\cdot$(x<sub>1</sub>+x<sub>2</sub>)] =   
[x<sub>1</sub>+x<sub>2</sub>+y<sub>1</sub>+y<sub>2</sub>,3$\cdot$x<sub>1</sub>+3$\cdot$x<sub>2</sub>]=
[x<sub>1</sub>+y<sub>1</sub>,3$\cdot$x<sub>1</sub>]+[x<sub>2</sub>+y<sub>2</sub>,3$\cdot$x<sub>2</sub>]=
f(x<sub>1</sub>,y<sub>1</sub>)+f(x<sub>2</sub>+y<sub>2</sub>)</style>  

<span style="color:orange">Luego, la función f(x,y) es una función lineal.</style>  

<span style="color:orange"> Ejemplo:  
    ¿La función f(x,y)=(x<sup>2</sup>,0) es una función lineal?  
</style>  
* <span style="color:orange">f(αx,αy)=((αx)<sup>2</sup>,0)=α<sup>2</sup>(x<sup>2</sup>,0)=α<sup>2</sup> f(x,y)

<span style="color:orange">Luego, la función f(x,y) no es una función lineal.</style>  

### Imagen de una función lineal

Dada una función f: $\mathbb{V}$ $\longrightarrow$ $\mathbb{W}$, se define como conjunto **imagen**:
> Imf = {**w** $\in$ $\mathbb{W}$ : $\exists$ **v** $\in$ $\mathbb{V}$ tal que **w**= f (**v**)} 

### Núcleo de una función lineal (Kernel)  

Dada una función f: $\mathbb{V}$ $\longrightarrow$ $\mathbb{W}$, se define como **núcleo** el conjunto de todos los vectpres de $\mathbb{V}$ cuya imagen es el vector nulo de $\mathbb{W}$:
> Kerf = {**v** $\in$ $\mathbb{V}$: f (**v**) = **0**}  


### Propiedad sobre dimensiones

Si f: $\mathbb{V}$<sup>n</sup>($\mathbb{K}$) $\longrightarrow$ $\mathbb{W}$<sup>m</sup>($\mathbb{K}$), entonces:  
> dim(Kerf)+dim(Imf)=n

### Clasificación de las funciones lineales

Dada una función f: $\mathbb{V}$ $\longrightarrow$ $\mathbb{W}$, se dice que:  
* f es **inyectiva** si para cada elemento de $\mathbb{V}$ existe un único elemento en  $\mathbb{W}$ . 
* f es **sobreyectiva** si cada elemento de $\mathbb{W}$ tiene por lo menos uno de $\mathbb{V}$ (a lo mejor más de uno) 
* f es **biyectiva** o **isomorfismo** si es inyectiva y sobreyectiva  (para cada w en $\mathbb{W}$, hay exactamente un v en $\mathbb{V}$ que cumple que f(v) = w)  

![No se puede mostrar](Images/function-mapping.gif)

Una función lineal es **biyectiva** si y solo si su kernel es un espacio vectorial trivial. 



### Endomorfismos 

Los **endomorfismos** son homomorfismos en los que coincide el espacio de llegada con el de salida:  
> f: $\mathbb{V}$<sup>n</sup>($\mathbb{K}$) $\longrightarrow$ $\mathbb{V}$<sup>n</sup>($\mathbb{K}$)

### Automorfismos

Los **automorfismos** son endomorfismos en los que además f es biyectiva.

## Transformaciones matriciales

Ahora estudiaremos la relación entre una matriz M y la función x → M * x.

Esta relación tiene dos caras:
* Partiendo de la matriz M, llegar a x → M * x  
* Pasar de la función x → M * x a la matriz M.




## De matrices a funciones

Dada una matriz M, definimos la función f(x) = M * x.  
  
Si M es una matriz R × C sobre $\mathbb{F}$: 
> f:$\mathbb{F}$<sup>C</sup> $\longrightarrow$ $\mathbb{F}$<sup>R</sup>

* El dominio de f es $\mathbb{F}$<sup>C</sup>  
* El codominio de f es $\mathbb{F}$<sup>R</sup>  

<span style="color:orange"> Ejemplo:  
Dada la matriz $
  M =
  \left[ {\begin{array}{cc}
   1 & 2 & 3 \\
   10 & 20 & 30 \\
  \end{array} } \right]
$, definimos f(x) = M $\cdot$ **x**.  
Por ejemplo, si tenemos el vector (2,2,-2) la imagen nos devuelve (0,0). Veámoslo: </style>  



In [2]:
import numpy as np

def funcion(v):
    M=np.matrix([
        [1,2,3],
        [10,20,30]
    ])
    f=M*v
    return f
funcion([[2],[2],[-2]])

matrix([[0],
        [0]])

<span style="color:orange">El dominio de f es $\mathbb{R}$<sup>3</sup> y su imagen es $\mathbb{R}$<sup>2</sup>. </style>  

# De funciones a matrices

Dada una función f:$\mathbb{F}$<sup>A</sup> $\longrightarrow$ $\mathbb{F}$<sup>B</sup> .  

Queremos calcular una matriz M tal que f(x) = M $\cdot$ **x**.  
* Como el dominio es $\mathbb{F}$<sup>A</sup>, sabemos que el vector de entrada es un A-vector.  
* Para que el producto M * x se pueda hacer, necesitamos que el número de columnas de M sea A.  
* Dado que la imagen es $\mathbb{F}$<sup>B</sup>, sabemos que la salida f (x) = M * x es un B-vector.   
* Para lograr eso, necesitamos que el número de filas de M sea B.  

Por tanto, M tiene que ser una matriz B × A.  
¿Cómo calculamos los valores de la matriz?  
* Escribimos una matriz M en términos de unos vectores desconocidos v<sub>i</sub>: M= [v<sub>1</sub> | ... |v<sub>n</sub> ].  
* Sean los vectores estándar: **e**<sub>1</sub>=(1,0,0,...,0,0),...,**e**<sub>n</sub>=(0,0,0,...,0,1):  
> f(**e**<sub>1</sub>) = [v<sub>1</sub> | ... |v<sub>n</sub> ] $\cdot$ (1,0,0,...,0,0) = v<sub>1</sub>  
> ...  
> f(**e**<sub>n</sub>) = [v<sub>1</sub> | ... |v<sub>n</sub> ] $\cdot$ (0,0,0,...,0,1) = v<sub>v</sub>  

<span style="color:orange"> Ejemplo: Escalado horizontal.</style>    
<img src="Images/shaping_stretch_horiz.jpg" style="width: 200px;"/>
<span style="color:orange"> Definimos s([x,y]) = función ampliación por dos en dirección horizontal.  
Sabemos que s([x , y ]) = M ∗ [x , y ] para alguna matriz M .</style>   
> * <span style="color:orange">Sabemos que s([1,0])=[2,0]  (porque aumentamos por dos en horizontal).</style>  
> * <span style="color:orange">Sabemos que s([0,1])=[0,1]  (porque no hay cambios en la vertical).</style>  

<span style="color:orange">Por lo tanto, la matriz M escritos los vectores en columnas:  
$
  M =
  \left[ {\begin{array}{cc}
   2 & 0 \\
   0 & 1 \\
  \end{array} } \right]
$</style>   

<span style="color:orange"> Veamos cómo escalar esto mismo en Python</style>

In [8]:
M=np.matrix([
    [2,0],
    [0,1]
])

def escalado(v):
    w=M*v
    return w

escalado([[1],[0]])

matrix([[2],
        [0]])

In [4]:
escalado([[0],[1]])

matrix([[0],
        [1]])

<span style="color:orange"> Pregunta:  
¿Y si la matriz M la hubiésemos escrito en filas en vez de en columnas?</style>

<span style="color:orange"> Ejemplo: Rotación de 90º.</style>    
<img src="Images/Rotation_90_clockwise_example.jpg" style="width: 200px;"/>
<span style="color:orange"> Definimos r([x,y]) = función rotación 90º.  
Sabemos que r([x , y ]) = M ∗ [x , y ] para alguna matriz M .</style>   
> * <span style="color:orange">Sabemos que r([1,0])=[0,-1]  .</style>  
> * <span style="color:orange">Sabemos que r([0,1])=[1,0]  .</style>  

<span style="color:orange">Por lo tanto:  
$
  M =
  \left[ {\begin{array}{cc}
   0 & 1 \\
   -1 & 0 \\
  \end{array} } \right]
$</style>   



In [9]:
M=np.matrix([
    [0,1],
    [-1,0]
])

def rotacion_90(v):
    w=M*v
    return w

rotacion_90([[1],[0]])

matrix([[ 0],
        [-1]])

In [10]:
rotacion_90([[0],[1]])

matrix([[1],
        [0]])

<span style="color:orange"> Ejemplo: Rotación de $\theta$º.</style>    
<span style="color:orange"> Definimos r([x,y]) = función rotación $\theta$º.  
Sabemos que r([x , y ]) = M ∗ [x , y ] para alguna matriz M .</style>   
> * <span style="color:orange">Sabemos que r([1,0])=[cos$\theta$,-sen$\theta$]  .</style>  
> * <span style="color:orange">Sabemos que r([0,1])=[sen$\theta$,cos$\theta$]  .</style>  

<span style="color:orange">Por lo tanto:  
$
  M =
  \left[ {\begin{array}{cc}
   cos\theta & sin\theta \\
   -sin\theta & cos\theta \\
  \end{array} } \right]
$</style>  



In [12]:
import math

def sen(grados):
    return math.sin(math.radians(grados))

def cos(grados):
    return math.sin(math.radians(grados))

def rotacion_theta(v,theta):
    M=np.matrix([
        [cos(theta),sen(theta)],
        [-sen(theta),cos(theta)]
    ])
    w=M*v
    return w

rotacion_theta([[0],[1]],90)

matrix([[1.],
        [1.]])

<span style="color:orange"> Ejemplo: Traslación.</style> 
<img src="Images/translation_example.jpg" style="width: 200px;"/>
<span style="color:orange"> Definimos t([x,y]) = función traslación por [1,2].  
Sabemos que t([x , y ]) = M ∗ [x , y ] para alguna matriz M .</style>   
> * <span style="color:orange">Sabemos que t([1,0])=[2,2]  .</style>  
> * <span style="color:orange">Sabemos que t([0,1])=[1,3]  .</style>  

<span style="color:orange">Por lo tanto:  
$
  M =
  \left[ {\begin{array}{cc}
   2 & 1 \\
   2 & 3 \\
  \end{array} } \right]
$</style>  



<span style="color:orange"> Ejemplo: Función identidad.  
Sea f(**x**)=**x**, con f:$\mathbb{R}$<sup>4</sup> $\longrightarrow$ $\mathbb{R}$<sup>4</sup>
Sabemos que f(**x**) = M ∗ **x** para alguna matriz M .  
Cogemos los generadores estándar:</style>  
* <span style="color:orange">e<sub>1</sub>=(1,0,0,0) $\longrightarrow$ f(e<sub>1</sub>)=e<sub>1</sub>, por lo que la primera columna es e<sub>1</sub></style>  
* <span style="color:orange">e<sub>2</sub>=(0,1,0,0) $\longrightarrow$ f(e<sub>2</sub>)=e<sub>2</sub>, por lo que la segunda columna es e<sub>2</sub></style>    
* <span style="color:orange">e<sub>3</sub>=(0,0,1,0) $\longrightarrow$ f(e<sub>3</sub>)=e<sub>3</sub>, por lo que la tercera columna es e<sub>3</sub></style>    
* <span style="color:orange">e<sub>4</sub>=(0,0,0,1) $\longrightarrow$ f(e<sub>4</sub>)=e<sub>4</sub>, por lo que la cuarta columna es e<sub>4</sub></style>    

<span style="color:orange">Por lo tanto:  
$
  M =
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & 0 \\
   0 & 1 & 0 & 0 \\
   0 & 0 & 1 & 0 \\
   0 & 0 & 0 & 1 \\
  \end{array} } \right]
$</style>  



¿Todas las transformaciones que hemos visto realmente son funciones lineales? 

<span style="color:orange"> Ejemplo:  
¿La función ampliación horizontal por dos s(x,y) es una función lineal?  
</style>  
* <span style="color:orange">s(αx,αy)=(2αx,αy)=α(2x,y)=α$\cdot$s(x,y)</style>  
* <span style="color:orange">s([x<sub>1</sub>,y<sub>1</sub>]+[x<sub>2</sub>,y<sub>2</sub>] = s(x<sub>1</sub>+x<sub>2</sub>,y<sub>1</sub>+y<sub>2</sub>) = (2[x<sub>1</sub>+x<sub>2</sub>],y<sub>1</sub>+y<sub>2</sub>) =  (2$\cdot$x<sub>1</sub>+2$\cdot$x<sub>2</sub>],y<sub>1</sub>+y<sub>2</sub>) = (2$\cdot$x<sub>1</sub>,y<sub>1</sub>)+(2$\cdot$x<sub>2</sub>,y<sub>2</sub>) = s(x<sub>1</sub>,y<sub>1</sub>)+s(x<sub>2</sub>,y<sub>2</sub>)</style>    

<span style="color:orange">Luego, la función s(x,y) es una función lineal.</style>  

<span style="color:orange">Si quisiésemos escribirlo en Python:</style>  

<span style="color:blue"> Ejemplo:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

<span style="color:orange"> Ejemplo:   
¿La función traslación por [1,2] t(x,y) es una función lineal?    
No es una función lineal ya que no cumple la primera propiedad.  
Sea por ejemplo el vector [2,3]:</style>     
* <span style="color:orange">t(5$\cdot$[2,3]) = t(10,15)=(11,17)</style>     
* <span style="color:orange">5$\cdot$ t[2,3] = 5$\cdot$(3,5)=(15,25).</style>    

Si f es una función lineal, f(**0**)=**0**.  

# Función composición de la multiplicación matricial. 

Sean las matrices A y B, con funciones f(**y**)=A $\cdot$ **y** y g(**x**)=B $\cdot$ **x**.  
Sea h(**x**)=(AB)$\cdot$**x**.  
Entonces se cumple que h = f o g.  

<span style="color:orange"> Ejemplo: 
Sean las matrices $
  A =
  \left[ {\begin{array}{cc}
   1 & 1 \\
   0 & 1 \\
  \end{array} } \right]
$ y $
  B =
  \left[ {\begin{array}{cc}
   1 & 0 \\
   1 & 1 \\
  \end{array} } \right]
$ . Comprobar que se cumple el lema de la función composición.</style>   


<span style="color:orange"> Luego, h=fog</style>   