# 12. Tensores

## ¿Qué son los tensores?

<img src="Images/tensores.png" style="width: 500px;"/>  

Un **tensor** es una generalización de vectores y matrices y se entiende fácilmente como una matriz multidimensional.  

Los tensores pueden ser clasificados según su orden como:  
> **Escalar** (Tensor de orden 0): Cantidad que tiene magnitud pero no dirección.  
> **Vector** (Tensor de orden 1): Cantidad que tiene magnitud y dirección.  
> **Matriz** (Tensor de orden 2): Cantidad que tiene magnitud y dos direcciones.  
> **Tensores de orden superior**  

La notación tensorial es muy parecida a la notación matricial con una letra mayúscula que representa un tensor y letras minúsculas con enteros subíndices que representan valores escalares dentro del tensor.  

$
 T =
  \left[\left( {\begin{array}{cc}
   t_{111} & t_{112} & t_{113} \\  
   t_{121} & t_{122} & t_{123} \\  
   t_{131} & t_{132} & t_{133} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   t_{211} & t_{212} & t_{213} \\  
   t_{221} & t_{222} & t_{223} \\  
   t_{231} & t_{232} & t_{233} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   t_{311} & t_{312} & t_{313} \\  
   t_{321} & t_{322} & t_{323} \\  
   t_{331} & t_{332} & t_{333} \\  
  \end{array} } \right)\right] 
$   


Muchas de las operaciones que se pueden realizar con escalares, vectores y matrices se pueden reformular para que se realicen con tensores.  

Al igual que los vectores y matrices, los tensores se pueden representar en Python usando la matriz N-dimensional (array).  

Un tensor se puede definir como una lista de listas.

<span style="color:orange">  Ejemplo: Un tensor de 3x3x3.    
$
 T =
  \left[\left( {\begin{array}{cc}
   1 & 2 & 3 \\  
   11 & 12 & 13 \\  
   21 & 22 & 23 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   4 & 5 & 6 \\  
   14 & 15 & 16 \\  
   24 & 25 & 26 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   7 & 8 & 9 \\  
   17 & 18 & 19 \\  
   27 & 28 & 29 \\  
  \end{array} } \right)\right] 
$   
Primero definimos filas, luego una lista de filas apiladas como columnas, luego una lista de columnas apiladas como niveles en un cubo.</style>  



In [1]:
from numpy import array
T = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]]
  ])
print(T)
# El tensor se imprime como una serie de matrices, una para cada capa. 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [2]:
# Vamos a imprimir la forma del tensor
print(T.shape)
# Pero...¿quién es quién?
# Veamoslos con otro ejemplo

(3, 3, 3)


<span style="color:orange">  Ejemplo: Un tensor de 3x2x1.    
$
 T =
  \left[\left( {\begin{array}{cc}
   1  \\  
   11 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   4 \\  
   14 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   7 \\  
   17 \\  
  \end{array} } \right)\right] 
$   
</style>  

In [3]:
from numpy import array
T2 = array([
  [[1],    [11]],
  [[4], [14]],
  [[7], [17]]  
  ])
print(T2)

[[[ 1]
  [11]]

 [[ 4]
  [14]]

 [[ 7]
  [17]]]


In [4]:
print(T2.shape)

(3, 2, 1)


In [5]:
T3= [[1, 2],  
       [[3, 4],  
       [[5, 6],  
       [[7,8] ]

SyntaxError: unexpected EOF while parsing (<ipython-input-5-64514507e40a>, line 4)

## Suma de tensores

La adición de dos tensores con las mismas dimensiones produce un nuevo tensor con las mismas dimensiones donde cada valor escalar es la adición de los escalares en los tensores padres.  

$
  A =
  \left[\left( {\begin{array}{cc}
   a_{111} & a_{112} & a_{113} \\  
   a_{121} & a_{122} & a_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a_{211} & a_{212} & a_{213} \\  
   a_{221} & a_{222} & a_{223} \\  
  \end{array} } \right)\right]  
$   

$
  B =
  \left[\left( {\begin{array}{cc}
   b_{111} & b_{112} & t_{113} \\  
   b_{121} & t_{122} & t_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b_{211} & b_{212} & b_{213} \\  
   b_{221} & b_{222} & b_{223} \\  
  \end{array} } \right)\right]  
$  

$
  A + B =
  \left[\left( {\begin{array}{cc}
   a_{111} + b_{111} & a_{112} + b_{112} & a_{113} + b_{113} \\  
   a_{121} + b_{121} & a_{122} + b_{122} & a_{123} + b_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a_{211} + b_{211} & a_{212} + b_{212} & a_{213} + b_{213} \\  
   a_{221} + b_{221} & a_{222} + b_{222} & a_{223} + b_{223} \\  
  \end{array} } \right)\right]  
$   

En NumPy, podemos agregar tensores directamente agregando matrices.

<span style="color:orange"> Ejemplo  
Queremos sumar el tensor $
 T1 =
  \left[\left( {\begin{array}{cc}
   1 & 2 & 3 \\  
   11 & 12 & 13 \\  
   21 & 22 & 23 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   4 & 5 & 6 \\  
   14 & 15 & 16 \\  
   24 & 25 & 26 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   7 & 8 & 9 \\  
   17 & 18 & 19 \\  
   27 & 28 & 29 \\  
  \end{array} } \right)\right] 
$ consigo mismo, esto es, T1 + T1 </style> 

In [6]:
from numpy import array
T1 = array([
  [[1,2,3], [11,12,13] , [21,22,23]],
  [[4,5,6], [14,15,16], [24,25,26]],
  [[7,8,9], [17,18,19], [27,28,29]],
  ])

S = T1 + T1
print(S)

[[[ 2  4  6]
  [22 24 26]
  [42 44 46]]

 [[ 8 10 12]
  [28 30 32]
  [48 50 52]]

 [[14 16 18]
  [34 36 38]
  [54 56 58]]]


<span style="color:orange"> ¿Y si quisiésemos hacer T1 - T1? </style> 

In [7]:
R = T1 - T1
print(R)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## Producto de tensores Hadamard

La multiplicación por elementos de un tensor con otro tensor con las mismas dimensiones da como resultado un nuevo tensor con las mismas dimensiones donde cada valor escalar es la multiplicación por elementos de los escalares en los tensores padres.  

La operación se conoce como Producto Hadamard para diferenciarla de la multiplicación tensorial. Aquí, utilizaremos el operador "o" para indicar el funcionamiento del producto Hadamard entre tensores.  

$
  A =
  \left[\left( {\begin{array}{cc}
   a_{111} & a_{112} & a_{113} \\  
   a_{121} & a_{122} & a_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a_{211} & a_{212} & a_{213} \\  
   a_{221} & a_{222} & a_{223} \\  
  \end{array} } \right)\right]  
$   

$
  B =
  \left[\left( {\begin{array}{cc}
   b_{111} & b_{112} & t_{113} \\  
   b_{121} & t_{122} & t_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b_{211} & b_{212} & b_{213} \\  
   b_{221} & b_{222} & b_{223} \\  
  \end{array} } \right)\right]  
$  

$
  A o B =
  \left( {\begin{array}{cc}
   a_{111} * b_{111}, a_{112} * b_{112}, a_{113} * b_{113} \\  
   a_{121} * b_{121}, a_{122} * b_{122}, a_{123} * b_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a_{211} * b_{211}, a_{212} * b_{212}, a_{213} * b_{213} \\  
   a_{221} * b_{221}, a_{222} * b_{222}, a_{223} * b_{223} \\  
  \end{array} } \right) , 
$   

<span style="color:orange"> Ejemplo  
Queremos hacer T1 * T1</style> 

In [8]:
H= T1 * T1
print(H)

[[[  1   4   9]
  [121 144 169]
  [441 484 529]]

 [[ 16  25  36]
  [196 225 256]
  [576 625 676]]

 [[ 49  64  81]
  [289 324 361]
  [729 784 841]]]


## División de tensores

$
  A =
  \left[\left( {\begin{array}{cc}
   a_{111} & a_{112} & a_{113} \\  
   a_{121} & a_{122} & a_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a_{211} & a_{212} & a_{213} \\  
   a_{221} & a_{222} & a_{223} \\  
  \end{array} } \right)\right]  
$   

$
  B =
  \left[\left( {\begin{array}{cc}
   b_{111} & b_{112} & t_{113} \\  
   b_{121} & t_{122} & t_{123} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b_{211} & b_{212} & b_{213} \\  
   b_{221} & b_{222} & b_{223} \\  
  \end{array} } \right)\right]  
$  

$
  A / B =
  \left( {\begin{array}{cc}
   \frac{a_{111}}{b_{111}} & \frac{a_{112}}{b_{112}} & \frac{a_{113}}{b_{113}} \\  
   \frac{a_{121}}{b_{121}} & \frac{a_{122}}{b_{122}} & \frac{a_{123}}{b_{123}} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   \frac{a_{211}}{b_{211}} & \frac{a_{212}}{b_{212}} & \frac{a_{121311}}{b_{213}} \\  
   \frac{a_{221}}{b_{221}} & \frac{a_{222}}{b_{222}} & \frac{a_{223}}{b_{223}} \\  
  \end{array} } \right)  
$   

<span style="color:orange"> Ejemplo 
Queremos hacer la división de T1 consigo mismo</style> 

In [9]:
D=T1/T1
print(D)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Producto tensor

El operador del producto tensor a menudo se denota como un círculo con una pequeña x en el centro. Lo designaremos aquí como "(x)".

Dado un tensor T1 con q dimensiones y tensor T2 con r dimensiones, el producto tensor o producto exterior$T1\otimes T2$ de estos tensores será un nuevo tensor con el orden de q + r o, dicho de otra manera, q + r dimensiones.

El producto tensor no se limita a tensores, sino que también se puede realizar en matrices y vectores, que pueden ser un buen lugar para practicar con el fin de desarrollar la intuición para dimensiones superiores.

Echemos un vistazo al **producto tensor para vectores**:

$\vec{a}^{\,} = (a_{1}, a_{2})$
 
$\vec{b}^{\,} = (b_{1}, b_{2})$
 
$\vec{c}^{\,} = \vec{a}^{\,}\otimes \vec{b}^{\,} =
  \left( {\begin{array}{cc}
   a_{1} * \left( {\begin{array}{cc}
                       b_{1}  \\  
                       b_{2}  \\  
                   \end{array} } \right) \\  
   a_{2} * \left( {\begin{array}{cc}
                       b_{1}  \\  
                       b_{2}  \\  
                   \end{array} } \right) \\  
  \end{array} } \right) =
  \left( {\begin{array}{cc}
   a_{1} * b_{1} & a_{1} * b_{2} \\  
   a_{2} * b_{1} & a_{2} * b_{2} \\  
  \end{array} } \right)  
$   


  
El **producto tensor para matrices**:  

$ A =
  \left( {\begin{array}{cc}
   a_{11} & a_{12} \\  
   a_{21} & a_{22} \\  
  \end{array} } \right)
$  

$ B =
  \left( {\begin{array}{cc}
   b_{11} & b_{12} \\  
   b_{21} & b_{22} \\  
  \end{array} } \right)
$  

$C = A\otimes B =
  \left( {\begin{array}{cc}
   a_{11}*\left( {\begin{array}{cc}
           b_{11} & b_{12} \\  
           b_{21} & b_{22} \\  
          \end{array} } \right) & a_{12} *\left( {\begin{array}{cc}
           b_{11} & b_{12} \\  
           b_{21} & b_{22} \\  
          \end{array} } \right) \\  
   a_{21}*\left( {\begin{array}{cc}
                       b_{11} & b_{12} \\  
                       b_{21} & b_{22} \\  
                   \end{array} } \right) 
         & a_{22} *\left( {\begin{array}{cc}
                                   b_{11} & b_{12} \\  
                                   b_{21} & b_{22} \\  
                            \end{array} } \right) \\ 
  \end{array} } \right) =
  \left( {\begin{array}{cc}
   a_{11} * b_{11} & a_{11} * b_{12} & a_{12} * b_{11} & a_{12} * b_{12} \\  
   a_{11} * b_{21} & a_{11} * b_{22} & a_{12} * b_{21} & a_{12} * b_{22} \\ 
   a_{21} * b_{11} & a_{21} * b_{12} & a_{22} * b_{11} & a_{22} * b_{12} \\ 
   a_{21} * b_{21} & a_{21} * b_{22} & a_{22} * b_{21} & a_{22} * b_{22} \\ 
  \end{array} } \right) 
$   

El producto tensor puede implementarse en NumPy usando la función de tensordot ().

<span style="color:orange"> Ejemplo:   
Dados los tensores de orden 1 (vectores) **a**=(1,2) y **b**=(3,4), vamos a calcular su producto tensorial.  
$\vec{a}^{\,}\otimes \vec{b}^{\,} =
 \left( {\begin{array}{cc}
   1 * \left( {\begin{array}{cc}
                       3  \\  
                       4  \\  
                   \end{array} } \right) \\  
   2 * \left( {\begin{array}{cc}
                       3  \\  
                       4  \\  
                   \end{array} } \right) \\  
  \end{array} } \right) =
  \left( {\begin{array}{cc}
   1 * 3 & 1 * 4 \\  
   2 * 3 & 2 * 4 \\  
  \end{array} } \right) =
  \left( {\begin{array}{cc}
   3 & 4 \\  
   6 & 8 \\  
  \end{array} } \right) 
$   
</style> 

In [10]:
from numpy import array
from numpy import tensordot
A = array([1,2])
B = array([3,4])
C = tensordot(A, B, axes=0) # Asumamos sin preguntas un segundo que axes=0
print(C)

[[3 4]
 [6 8]]


Vamos a hablar un poco de cómo especificar los argumentos de **tensordot**.

**tensordot(a,b,axes)**:  
> a y b son los tensores a operar.  
> axes: Es el eje sobre el que se operan los tensores. Opera sobre los últimos N ejes de a y los primeros N ejes de b en orden.    
>> axes=0: $A\otimes B$. Es el producto tensor del que venimos hablando.   
>> axes=1: $A \cdot B$. Se llama **producto tensor de contracción simple**  
>> axes=2: A : B . Se llama **producto tensor de contracción doble**. Es el valor por defecto si no se especifica ninguno.  
>> axes=(n1,n2): el primer valor aplica a "a" y el segundo valor a "b"

<span style="color:orange"> Ejemplo:  
Vamos a ver el producto tensor con los tensores de orden 2 (matrices) A=$\left( {\begin{array}{cc}
                                                                                         1 & 2  \\  
                                                                                         3 & 4  \\  
                                                                                   \end{array} } 
                                                                            \right)$
y B=$\left( {\begin{array}{cc}
                   5 & 10  \\  
                   7 & 9  \\  
             \end{array} } 
     \right)$.  
El producto tensorial (axes=0) sabemos que tendrá dimensión 8 (2x2x2):</style>    
      
<span style="color:orange">$A\otimes B = \left( {\begin{array}{cc}
                                                        1 & 2  \\  
                                                        3 & 4  \\  
                                                 \end{array} } 
                                          \right) \otimes 
                                          \left( {\begin{array}{cc}
                                                         5 & 6  \\  
                                                         7 & 8  \\  
                                                   \end{array} } 
                                          \right) 
                                        = \left( {\begin{array}{cc}
                                                        1 * \left( {\begin{array}{cc}
                                                                             5 & 6  \\  
                                                                             7 & 8  \\  
                                                                     \end{array} } 
                                                             \right) 
                                                       & 2 * \left( {\begin{array}{cc}
                                                                             5 & 6  \\  
                                                                             7 & 8  \\  
                                                                     \end{array} } 
                                                             \right)  \\  ,
                                                       3 * \left( {\begin{array}{cc}
                                                                             5 & 6  \\  
                                                                             7 & 8  \\  
                                                                     \end{array} } 
                                                             \right)
                                                      & 4 * \left( {\begin{array}{cc}
                                                                             5 & 6  \\  
                                                                             7 & 8  \\  
                                                                     \end{array} } 
                                                             \right) \\  
                                                 \end{array} } 
                                          \right)
                                         = \left( {\begin{array}{cc}
                                                        \left( {\begin{array}{cc}
                                                                             1 * 5 & 1 * 6  \\  
                                                                             1 * 7 & 1 * 8  \\  
                                                                     \end{array} } 
                                                             \right) 
                                                       & \left( {\begin{array}{cc}
                                                                              2 *5 & 2 * 6  \\  
                                                                              2 *7 &  2 *8  \\  
                                                                     \end{array} } 
                                                             \right)  \\  ,
                                                      \left( {\begin{array}{cc}
                                                                              3 * 5 & 3 * 6  \\  
                                                                              3 * 7 & 3 * 8  \\  
                                                                     \end{array} } 
                                                             \right)
                                                      & \left( {\begin{array}{cc}
                                                                             4 * 5 & 4 * 6  \\  
                                                                             4 * 7 & 4 * 8  \\  
                                                                     \end{array} } 
                                                             \right) \\  
                                                 \end{array} } 
                                          \right)
                                         = \left( {\begin{array}{cc}
                                                        \left( {\begin{array}{cc}
                                                                             5 & 6  \\  
                                                                             7 & 8  \\  
                                                                     \end{array} } 
                                                             \right) 
                                                       & \left( {\begin{array}{cc}
                                                                              10 & 12  \\  
                                                                              14 & 16  \\  
                                                                     \end{array} } 
                                                             \right)  \\  ,
                                                      \left( {\begin{array}{cc}
                                                                              15 & 18  \\  
                                                                              21 & 24  \\  
                                                                     \end{array} } 
                                                             \right)
                                                      & \left( {\begin{array}{cc}
                                                                             20 & 24  \\  
                                                                             28 & 32  \\  
                                                                     \end{array} } 
                                                             \right) \\  
                                                 \end{array} } 
                                          \right)
                            $</style> 

In [11]:
from numpy import array

# Vamos a definir las matrices automáticamente
A = array(range(1, 5))
A
# Cuidado! No tiene la forma que buscamos

array([1, 2, 3, 4])

In [12]:
# Le damos forma
A.shape=(2,2)
A

array([[1, 2],
       [3, 4]])

In [13]:
# Definimos B
B = array(range(5, 9))
B.shape=(2,2)
B

array([[5, 6],
       [7, 8]])

In [14]:
from numpy import tensordot
C = tensordot(A, B, axes=0)
print(C)

[[[[ 5  6]
   [ 7  8]]

  [[10 12]
   [14 16]]]


 [[[15 18]
   [21 24]]

  [[20 24]
   [28 32]]]]


Vamos a hablar ahora de los **productos tensores de contracción**. 

La contracción de tensores es una operación que reduce el orden total de un tensor.    

El **producto tensor de contracción simple** $A \cdot B$.  

En matrices, es el producto matricial tal y como lo estudiamos.


<span style="color:orange"> Ejemplo:  
Vamos a ver el producto tensor de contracción simple con los tensores de orden 2 de antes A=$\left( {\begin{array}{cc}
                                                                                         1 & 2  \\  
                                                                                         3 & 4  \\  
                                                                                   \end{array} } 
                                                                            \right)$
y B=$\left( {\begin{array}{cc}
                   5 & 10  \\  
                   7 & 9  \\  
             \end{array} } 
     \right)$.  
</style>    
      
<span style="color:orange">$A\cdot B = \left( {\begin{array}{cc}
                                                        1 & 2  \\  
                                                        3 & 4  \\  
                                                 \end{array} } 
                                          \right) \cdot 
                                          \left( {\begin{array}{cc}
                                                         5 & 6  \\  
                                                         7 & 8  \\  
                                                   \end{array} } 
                                          \right) 
                                        = \left( {\begin{array}{cc}
                                                                 1\cdot5+2\cdot7 & 1\cdot6+2\cdot8  \\  
                                                                 3\cdot5+4\cdot7 & 3\cdot6+4\cdot8  \\  
                                                   \end{array} } 
                                          \right) 
                                         = \left( {\begin{array}{cc}
                                                                 19 & 22  \\  
                                                                 43 & 50  \\  
                                                   \end{array} } 
                                          \right) 
                            $</style> 


In [15]:
from numpy import tensordot
C = tensordot(A, B, axes=1)
print(C)     

[[19 22]
 [43 50]]


<span style="color:orange"> Ejemplo:  
Vamos a ver el producto tensor de contracción simple con dos tensores A=$\left(\left( {\begin{array}{cc}
                                                                                         1 & 2 & 3 \\  
                                                                                         4 & 5 & 6 \\ 
                                                                                         7 & 8 & 9 \\
                                                                                   \end{array} } 
                                                                                \right),
                                                                                \left( {\begin{array}{cc}
                                                                                         10 & 11 & 12 \\  
                                                                                         13 & 14 & 15 \\ 
                                                                                         16 & 17 & 18 \\
                                                                                   \end{array} } 
                                                                                \right),
                                                                                \left( {\begin{array}{cc}
                                                                                         20 & 21 & 22 \\  
                                                                                         23 & 24 & 25 \\ 
                                                                                         26 & 27 & 28 \\
                                                                                   \end{array} } 
                                                                                \right)
                                                                            \right)$  
y B=$\left(\left( {\begin{array}{cc}
                          a1 & b1 & c1 \\  
                          d1 & e1 & f1 \\ 
                          g1 & h1 & i1 \\ 
                   \end{array} } 
           \right),
           \left( {\begin{array}{cc}
                          a2 & b2 & c2 \\  
                          d2 & e2 & f2 \\ 
                          g2 & h2 & i2 \\ 
                   \end{array} } 
           \right),
           \left( {\begin{array}{cc}
                          a3 & b3 & c3 \\  
                          d3 & e3 & f3 \\ 
                          g3 & h3 & i3 \\ 
                   \end{array} } 
           \right)
      \right)$.  
</style>    
      


In [16]:
# Primero lo vamos a calcular en Python
from numpy import array
from numpy import tensordot

A=array([
  [[1,2,3], [4,5,6], [7,8,9]],
  [[10,11,12], [13,24,15], [16,17,18]],
  [[20,21,22], [23,24,25], [26,27,28]],
  ])

B=array([
  [['a1','b1','c1'], ['d1','e1','f1'], ['g1','h1','i1']],
  [['a2','b2','c2'], ['d2','e2','f2'], ['g2','h2','i2']],
  [['a3','b3','c3'], ['d3','e3','f3'], ['g3','h3','i3']],
  ],dtype=object)

C = tensordot(A, B, axes=1)
print(C) 

[[[['a1a2a2a3a3a3' 'b1b2b2b3b3b3' 'c1c2c2c3c3c3']
   ['d1d2d2d3d3d3' 'e1e2e2e3e3e3' 'f1f2f2f3f3f3']
   ['g1g2g2g3g3g3' 'h1h2h2h3h3h3' 'i1i2i2i3i3i3']]

  [['a1a1a1a1a2a2a2a2a2a3a3a3a3a3a3' 'b1b1b1b1b2b2b2b2b2b3b3b3b3b3b3'
    'c1c1c1c1c2c2c2c2c2c3c3c3c3c3c3']
   ['d1d1d1d1d2d2d2d2d2d3d3d3d3d3d3' 'e1e1e1e1e2e2e2e2e2e3e3e3e3e3e3'
    'f1f1f1f1f2f2f2f2f2f3f3f3f3f3f3']
   ['g1g1g1g1g2g2g2g2g2g3g3g3g3g3g3' 'h1h1h1h1h2h2h2h2h2h3h3h3h3h3h3'
    'i1i1i1i1i2i2i2i2i2i3i3i3i3i3i3']]

  [['a1a1a1a1a1a1a1a2a2a2a2a2a2a2a2a3a3a3a3a3a3a3a3a3'
    'b1b1b1b1b1b1b1b2b2b2b2b2b2b2b2b3b3b3b3b3b3b3b3b3'
    'c1c1c1c1c1c1c1c2c2c2c2c2c2c2c2c3c3c3c3c3c3c3c3c3']
   ['d1d1d1d1d1d1d1d2d2d2d2d2d2d2d2d3d3d3d3d3d3d3d3d3'
    'e1e1e1e1e1e1e1e2e2e2e2e2e2e2e2e3e3e3e3e3e3e3e3e3'
    'f1f1f1f1f1f1f1f2f2f2f2f2f2f2f2f3f3f3f3f3f3f3f3f3']
   ['g1g1g1g1g1g1g1g2g2g2g2g2g2g2g2g3g3g3g3g3g3g3g3g3'
    'h1h1h1h1h1h1h1h2h2h2h2h2h2h2h2h3h3h3h3h3h3h3h3h3'
    'i1i1i1i1i1i1i1i2i2i2i2i2i2i2i2i3i3i3i3i3i3i3i3i3']]]


 [[['a1a1a1a1a1a1a1a

¿Cómo sería entonces el productor tensor de contracción simple para estos tensores?  

$
  A =
  \left[\left( {\begin{array}{cc}
   a_{111} & a_{112} & a_{113} \\  
   a_{121} & a_{122} & a_{123} \\  
   a_{131} & a_{132} & a_{133} \\ 
  \end{array} } \right)
  \left( {\begin{array}{cc}
   a_{211} & a_{212} & a_{213} \\  
   a_{221} & a_{222} & a_{223} \\ 
   a_{231} & a_{232} & a_{233} \\
  \end{array} } \right)
  \left( {\begin{array}{cc}
   a_{311} & a_{312} & a_{313} \\  
   a_{321} & a_{322} & a_{323} \\ 
   a_{331} & a_{332} & a_{333} \\
  \end{array} }\right)\right]  
$   

$
  B =
  \left[\left( {\begin{array}{cc}
   b_{111} & b_{112} & t_{113} \\  
   b_{121} & t_{122} & t_{123} \\  
   b_{131} & t_{132} & t_{133} \\ 
  \end{array} } \right) 
  \left( {\begin{array}{cc}
   b_{211} & b_{212} & b_{213} \\  
   b_{221} & b_{222} & b_{223} \\ 
   b_{231} & b_{232} & b_{233} \\  
  \end{array} } \right)
  \left( {\begin{array}{cc}
   b_{311} & b_{312} & b_{313} \\  
   b_{321} & b_{322} & b_{323} \\ 
   b_{331} & b_{332} & b_{333} \\  
  \end{array} }\right)\right]  
$  

$A\cdot B = \left[\left( {\begin{array}{cc}
   a_{111} & a_{112} & a_{113} \\  
   a_{121} & a_{122} & a_{123} \\  
   a_{131} & a_{132} & a_{133} \\ 
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a_{211} & a_{212} & a_{213} \\  
   a_{221} & a_{222} & a_{223} \\ 
   a_{231} & a_{232} & a_{233} \\
  \end{array} } \right)
  \left( {\begin{array}{cc}
   a_{311} & a_{312} & a_{313} \\  
   a_{321} & a_{322} & a_{323} \\ 
   a_{331} & a_{332} & a_{333} \\
  \end{array} }\right)\right] 
  \cdot
  \left[\left( {\begin{array}{cc}
   b_{111} & b_{112} & t_{113} \\  
   b_{121} & t_{122} & t_{123} \\  
   b_{131} & t_{132} & t_{133} \\ 
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b_{211} & b_{212} & b_{213} \\  
   b_{221} & b_{222} & b_{223} \\ 
   b_{231} & b_{232} & b_{233} \\  
  \end{array} } \right)
  \left( {\begin{array}{cc}
   b_{311} & b_{312} & b_{313} \\  
   b_{321} & b_{322} & b_{323} \\ 
   b_{331} & b_{332} & b_{333} \\  
  \end{array} }\right)\right] = 
  \left[\left(\left({\begin{array}{cc}
                            \sum a_{11i} \cdot b_{i11} & \sum a_{11i} \cdot b_{i12} & \sum a_{11i} \cdot b_{i13} \\                             \sum a_{11i} \cdot b_{i21} & \sum a_{11i} \cdot b_{i22} & \sum a_{11i} \cdot b_{i23} \\                             \sum a_{11i} \cdot b_{i31} & \sum a_{11i} \cdot b_{i32} & \sum a_{11i} \cdot b_{i33} \\ 
              \end{array} }\right)
              \left({\begin{array}{cc}
                            \sum a_{12i} \cdot b_{i11} & \sum a_{12i} \cdot b_{i12} & \sum a_{12i} \cdot b_{i13} \\                             \sum a_{12i} \cdot b_{i21} & \sum a_{12i} \cdot b_{i22} & \sum a_{12i} \cdot b_{i23} \\                             \sum a_{12i} \cdot b_{i31} & \sum a_{12i} \cdot b_{i32} & \sum a_{12i} \cdot b_{i33} \\ 
              \end{array} }\right)
              \left({\begin{array}{cc}
                            \sum a_{13i} \cdot b_{i11} & \sum a_{13i} \cdot b_{i12} & \sum a_{13i} \cdot b_{i13} \\                             \sum a_{13i} \cdot b_{i21} & \sum a_{13i} \cdot b_{i22} & \sum a_{13i} \cdot b_{i23} \\                             \sum a_{13i} \cdot b_{i31} & \sum a_{13i} \cdot b_{i32} & \sum a_{13i} \cdot b_{i33} \\                      \end{array} }\right)
        \right) ,
        \left(\left({\begin{array}{cc}
                            \sum a_{21i} \cdot b_{i11} & \sum a_{21i} \cdot b_{i12} & \sum a_{21i} \cdot b_{i13} \\                             \sum a_{21i} \cdot b_{i21} & \sum a_{21i} \cdot b_{i22} & \sum a_{21i} \cdot b_{i23} \\                             \sum a_{21i} \cdot b_{i31} & \sum a_{21i} \cdot b_{i32} & \sum a_{21i} \cdot b_{i33} \\ 
              \end{array} }\right)
              \left({\begin{array}{cc}
                            \sum a_{22i} \cdot b_{i11} & \sum a_{22i} \cdot b_{i12} & \sum a_{22i} \cdot b_{i13} \\                             \sum a_{22i} \cdot b_{i21} & \sum a_{22i} \cdot b_{i22} & \sum a_{22i} \cdot b_{i23} \\                             \sum a_{22i} \cdot b_{i31} & \sum a_{22i} \cdot b_{i32} & \sum a_{22i} \cdot b_{i33} \\ 
              \end{array} }\right)
              \left({\begin{array}{cc}
                            \sum a_{23i} \cdot b_{i11} & \sum a_{23i} \cdot b_{i12} & \sum a_{23i} \cdot b_{i13} \\                             \sum a_{23i} \cdot b_{i21} & \sum a_{23i} \cdot b_{i22} & \sum a_{23i} \cdot b_{i23} \\                             \sum a_{23i} \cdot b_{i31} & \sum a_{23i} \cdot b_{i32} & \sum a_{23i} \cdot b_{i33} \\                      \end{array} }\right)
        \right) ,
        \left(\left({\begin{array}{cc}
                            \sum a_{31i} \cdot b_{i11} & \sum a_{31i} \cdot b_{i12} & \sum a_{31i} \cdot b_{i13} \\                             \sum a_{31i} \cdot b_{i21} & \sum a_{31i} \cdot b_{i22} & \sum a_{31i} \cdot b_{i23} \\                             \sum a_{31i} \cdot b_{i31} & \sum a_{31i} \cdot b_{i32} & \sum a_{31i} \cdot b_{i33} \\ 
              \end{array} }\right)
              \left({\begin{array}{cc}
                            \sum a_{32i} \cdot b_{i11} & \sum a_{32i} \cdot b_{i12} & \sum a_{32i} \cdot b_{i13} \\                             \sum a_{32i} \cdot b_{i21} & \sum a_{32i} \cdot b_{i22} & \sum a_{32i} \cdot b_{i23} \\                             \sum a_{32i} \cdot b_{i31} & \sum a_{32i} \cdot b_{i32} & \sum a_{32i} \cdot b_{i33} \\ 
              \end{array} }\right)
              \left({\begin{array}{cc}
                            \sum a_{33i} \cdot b_{i11} & \sum a_{33i} \cdot b_{i12} & \sum a_{33i} \cdot b_{i13} \\                             \sum a_{33i} \cdot b_{i21} & \sum a_{33i} \cdot b_{i22} & \sum a_{33i} \cdot b_{i23} \\                             \sum a_{33i} \cdot b_{i31} & \sum a_{33i} \cdot b_{i32} & \sum a_{33i} \cdot b_{i33} \\                      \end{array} }\right)
        \right) 
 \right]
                            $

El resultado nos devuelve:  
* Un tensor compuesto por tres matrices. 
* La primera matriz se forma con los elementos de la primera matriz de A multiplicado matricialmente con la matriz B completa (la primera matriz es el elemento de la primera fila y primera columna de la primera matriz de A)  
* La segunda matriz son los elementos de la segunda matriz del tensor A multiplicada matricialmente con la matriz B.   
* La tercera matriz son los elementos de la tercera matriz del tensor A multiplicada matricialmente con la matriz B.   



In [17]:
from numpy import array
from numpy import tensordot

TA=array([
  [[1,2,3], [4,5,6], [7,8,9]],
  [[10,11,12], [13,24,15], [16,17,18]],
  [[20,21,22], [23,24,25], [26,27,28]],
  ])

TB=array([
  [['a1','b1','c1'], ['d1','e1','f1'], ['g1','h1','i1']],
  [['a2','b2','c2'], ['d2','e2','f2'], ['g2','h2','i2']],
  [['a3','b3','c3'], ['d3','e3','f3'], ['g3','h3','i3']],
  ],dtype=object)

TC = tensordot(TA, TB) # No hace falta indicar axes=2 porque es su valor por defecto
print(C) 

[[[['a1a2a2a3a3a3' 'b1b2b2b3b3b3' 'c1c2c2c3c3c3']
   ['d1d2d2d3d3d3' 'e1e2e2e3e3e3' 'f1f2f2f3f3f3']
   ['g1g2g2g3g3g3' 'h1h2h2h3h3h3' 'i1i2i2i3i3i3']]

  [['a1a1a1a1a2a2a2a2a2a3a3a3a3a3a3' 'b1b1b1b1b2b2b2b2b2b3b3b3b3b3b3'
    'c1c1c1c1c2c2c2c2c2c3c3c3c3c3c3']
   ['d1d1d1d1d2d2d2d2d2d3d3d3d3d3d3' 'e1e1e1e1e2e2e2e2e2e3e3e3e3e3e3'
    'f1f1f1f1f2f2f2f2f2f3f3f3f3f3f3']
   ['g1g1g1g1g2g2g2g2g2g3g3g3g3g3g3' 'h1h1h1h1h2h2h2h2h2h3h3h3h3h3h3'
    'i1i1i1i1i2i2i2i2i2i3i3i3i3i3i3']]

  [['a1a1a1a1a1a1a1a2a2a2a2a2a2a2a2a3a3a3a3a3a3a3a3a3'
    'b1b1b1b1b1b1b1b2b2b2b2b2b2b2b2b3b3b3b3b3b3b3b3b3'
    'c1c1c1c1c1c1c1c2c2c2c2c2c2c2c2c3c3c3c3c3c3c3c3c3']
   ['d1d1d1d1d1d1d1d2d2d2d2d2d2d2d2d3d3d3d3d3d3d3d3d3'
    'e1e1e1e1e1e1e1e2e2e2e2e2e2e2e2e3e3e3e3e3e3e3e3e3'
    'f1f1f1f1f1f1f1f2f2f2f2f2f2f2f2f3f3f3f3f3f3f3f3f3']
   ['g1g1g1g1g1g1g1g2g2g2g2g2g2g2g2g3g3g3g3g3g3g3g3g3'
    'h1h1h1h1h1h1h1h2h2h2h2h2h2h2h2h3h3h3h3h3h3h3h3h3'
    'i1i1i1i1i1i1i1i2i2i2i2i2i2i2i2i3i3i3i3i3i3i3i3i3']]]


 [[['a1a1a1a1a1a1a1a

El **producto tensor de doble contracción** A : B.  

<span style="color:orange"> Ejemplo:  
Vamos a ver el producto tensor de doble contracción con los tensores de orden 2 T3=$\left( {\begin{array}{cc}
                                                                                         1 & 2  \\  
                                                                                         3 & 4  \\  
                                                                                   \end{array} } 
                                                                            \right)$
y T4=$\left( {\begin{array}{cc}
                   a & b  \\  
                   c & d  \\  
             \end{array} } 
     \right)$.  
</style>    
      
<span style="color:orange">$T3\cdot T4 = \left( {\begin{array}{cc}
                                                        1 & 2  \\  
                                                        3 & 4  \\  
                                                 \end{array} } 
                                          \right) \cdot 
                                          \left( {\begin{array}{cc}
                                                         a & b  \\  
                                                         c & d  \\  
                                                   \end{array} } 
                                          \right) 
                                        = 1\cdot a+2\cdot b+3\cdot c+4\cdot d  \\  
                            $</style> 

In [18]:
# Son los vectores A y B de antes  
from numpy import array
from numpy import tensordot
T1 = array((1, 2, 3, 4))
T1.shape = (2, 2)
T2 = array(('a', 'b', 'c', 'd'), dtype=object)
T2.shape = (2, 2)
C = tensordot(T1, T2) # No hace falta indicar axes=2 ya que es su valor por defecto
print(C)     

abbcccdddd


<span style="color:orange"> Ejemplo:  
Vamos a ver el producto tensor de doble contracción con dos tensores A=$\left(\left( {\begin{array}{cc}
                                                                                         1 & 2 & 3 \\  
                                                                                         4 & 5 & 6 \\ 
                                                                                         7 & 8 & 9 \\
                                                                                   \end{array} } 
                                                                                \right),
                                                                                \left( {\begin{array}{cc}
                                                                                         10 & 11 & 12 \\  
                                                                                         13 & 14 & 15 \\ 
                                                                                         16 & 17 & 18 \\
                                                                                   \end{array} } 
                                                                                \right),
                                                                                \left( {\begin{array}{cc}
                                                                                         20 & 21 & 22 \\  
                                                                                         23 & 24 & 25 \\ 
                                                                                         26 & 27 & 28 \\
                                                                                   \end{array} } 
                                                                                \right)
                                                                            \right)$  
y B=$\left(\left( {\begin{array}{cc}
                          a1 & b1 & c1 \\  
                          d1 & e1 & f1 \\ 
                          g1 & h1 & i1 \\ 
                   \end{array} } 
           \right),
           \left( {\begin{array}{cc}
                          a2 & b2 & c2 \\  
                          d2 & e2 & f2 \\ 
                          g2 & h2 & i2 \\ 
                   \end{array} } 
           \right),
           \left( {\begin{array}{cc}
                          a3 & b3 & c3 \\  
                          d3 & e3 & f3 \\ 
                          g3 & h3 & i3 \\ 
                   \end{array} } 
           \right)
      \right)$.  
</style>    
      



In [19]:
from numpy import array
from numpy import tensordot

A=array([
  [[1,2,3], [4,5,6], [7,8,9]],
  [[10,11,12], [13,24,15], [16,17,18]],
  [[20,21,22], [23,24,25], [26,27,28]],
  ])

B=array([
  [['a1','b1','c1'], ['d1','e1','f1'], ['g1','h1','i1']],
  [['a2','b2','c2'], ['d2','e2','f2'], ['g2','h2','i2']],
  [['a3','b3','c3'], ['d3','e3','f3'], ['g3','h3','i3']],
  ],dtype=object)

C = tensordot(A, B)
print(C) 

[['a1d1d1g1g1g1a2a2a2a2d2d2d2d2d2g2g2g2g2g2g2a3a3a3a3a3a3a3d3d3d3d3d3d3d3d3g3g3g3g3g3g3g3g3g3'
  'b1e1e1h1h1h1b2b2b2b2e2e2e2e2e2h2h2h2h2h2h2b3b3b3b3b3b3b3e3e3e3e3e3e3e3e3h3h3h3h3h3h3h3h3h3'
  'c1f1f1i1i1i1c2c2c2c2f2f2f2f2f2i2i2i2i2i2i2c3c3c3c3c3c3c3f3f3f3f3f3f3f3f3i3i3i3i3i3i3i3i3i3']
 ['a1a1a1a1a1a1a1a1a1a1d1d1d1d1d1d1d1d1d1d1d1g1g1g1g1g1g1g1g1g1g1g1g1a2a2a2a2a2a2a2a2a2a2a2a2a2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3g3g3g3g3g3g3g3g3g3g3g3g3g3g3g3g3g3g3'
  'b1b1b1b1b1b1b1b1b1b1e1e1e1e1e1e1e1e1e1e1e1h1h1h1h1h1h1h1h1h1h1h1h1b2b2b2b2b2b2b2b2b2b2b2b2b2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2h2h2h2h2h2h2h2h2h2h2h2h2h2h2h2b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3h3h3h3h3h3h3h3h3h3h3h3h3h3h3h3h3h3h3'
  'c1c1c1c1c1c1c1c1c1c1f1f1f1f1f1f1f1f1f1f1f1i1i1i1i1i1i1i1i1i1i1i1i1c2c2c2c2c2c2c2c2c2c2c2c2c2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2i2i2i2i2i2i2i2i2i

Nos falta ver cuando **axes=(n1,n2)**.  

In [20]:
T5 = array(range(1, 9))
T5.shape = (2, 2, 2)
T5
# Es un tensor compuesto por dos matrices de orden 2x2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
T6 = array(('a', 'b', 'c', 'd'), dtype=object)
T6.shape = (2, 2)
T6
# Es una matriz

array([['a', 'b'],
       ['c', 'd']], dtype=object)

In [22]:
tensordot(T5, T6, (0, 1))

array([[['abbbbb', 'cddddd'],
        ['aabbbbbb', 'ccdddddd']],

       [['aaabbbbbbb', 'cccddddddd'],
        ['aaaabbbbbbbb', 'ccccdddddddd']]], dtype=object)