# 7. Matrices

## ¿Qué es una matriz?

Si A es una matriz m × n, esto es, una matriz con m filas y n columnas, entonces la entrada escalar en la i-ésima  la y la j-ésima columna de A se denota mediante aij y se llama entrada (i, j) de A.  
$
  M=
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1j}  \\
   a_{21} & a_{22}  & ... & a_{2j}  \\
   ... & ...  & ... & ...  \\
   a_{i1} & a_{i2}  & ... & a_{ij}  \\
  \end{array} } \right]
$  
Las entradas diagonales en una matriz m × n A = [aij] son a<sub>11</sub>, a<sub>22</sub>, a<sub>33</sub>, ... , y forman la **diagonal principal** de A.  
Una **matriz diagonal** es una matriz cuadrada cuyas entradas no diagonales son cero.  
Un ejemplo es la matriz identidad n × n, I<sub>n</sub>.  
$
  I_n=
  \left[ {\begin{array}{cc}
   1 & 0  & ... & 0  \\
   0 & 1  & ... & 0  \\
   ... & ...  & ... & ...  \\
   0 & 0  & ... & 1  \\
  \end{array} } \right]
$  
Una matriz de m × n cuyas entradas son todas cero es una **matriz cero** y se escribe como 0. El tamaño de 0, por lo general, resulta evidente a partir del contexto.  

La representación en Python puede venir dada de varias maneras diferentes. Nosotros vamos a ver:  
* Arrays  
* Matrices  

NOTA: Las ventajas de usar matrices en el fondo son muy pocas y además la mayoría de funciones de NumPy maneja arrays, así que tendrías que convertir entre ambos tipos constantemente. Vamos a mostrar brevemente el uso de las matrices también, pero mejor utilizar arrays y olvidarse.


<span style="color:orange"> Ejemplo: Escribamos en Python la siguiente matriz: 
$
  A=
  \left[ {\begin{array}{cc}
   1 & 2  & 3   \\
   10 & 20  & 30   \\
  \end{array} } \right]
$.  
Primero con matrices:</style> 

In [1]:
import numpy as np
np.matrix([
   [1, 2, 3],
   [10, 20, 30]
   ])

matrix([[ 1,  2,  3],
        [10, 20, 30]])

<span style="color:orange">Ahora con arrays:</style> 

In [2]:
import numpy as np
A = np.array([[1, 2,3], [10,20,30]])
A

array([[ 1,  2,  3],
       [10, 20, 30]])

<span style="color:orange"> Ejemplo: Ahora queremos generar la matriz identidad de orden 4
</style> 

In [3]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<span style="color:orange"> Ejemplo: Escribamos en Python la matriz de 4x3 con unos en una diagonal y ceros en el resto de elementos/style> 

In [4]:
import numpy as np
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

<span style="color:orange"> Con el siguiente parámetro podemos controlar qué diagonal se rellena.</style> 

In [5]:
import numpy as np
np.eye(4, 3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<span style="color:orange"> Ejemplo: Ahora queremos generar la matriz cero de orden 4
</style> 

In [6]:
import numpy as np
A = np.zeros((4, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Suma de matrices

* Se dice que dos **matrices** son **iguales** si tienen el mismo tamaño, es decir, el mismo número de filas y de columnas, y sus columnas correspondientes son iguales.  
* Si A y B son matrices m × n, entonces la suma A + B es la matriz m × n cuyas columnas son las sumas de las columnas correspondientes de A y B. Como la suma vectorial de las columnas se realiza por entradas, cada entrada en A + B es la suma de las entradas correspondientes de A y B. 
* La suma A + B está definida sólo cuando A y B son del mismo tamaño.  

<span style="color:orange"> Ejemplo: Queremos sumar las matrices $
  matriz1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$ y $
  matriz2=
  \left[ {\begin{array}{cc}
   -1 & 2 \\
   1 & -2\\
  \end{array} } \right]
$.  
Primero con matrices:</style> 

In [7]:
import numpy as np

matriz1 = np.matrix(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.matrix(
    [[-1, 2],
     [1, -2]]
)

matriz1 + matriz2

matrix([[ 0,  6],
        [ 3, -2]])

<span style="color:orange"> Ahora con arrays:</style> 

In [8]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.array(
    [[-1, 2],
     [1, -2]]
)

matriz1 + matriz2

array([[ 0,  6],
       [ 3, -2]])

## Multiplicación de una matriz por un escalar

* Si r es un escalar y A es una matriz, entonces el múltiplo escalar rA es la matriz cuyas columnas son r veces las columnas correspondientes de A. 
* Al igual que con los vectores, se de ne −A como (−1)A y se escribe A − B en lugar de A + (−1)B.

<span style="color:orange"> Ejemplo: Queremos multiplicar la $
  matriz1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$ por 2.  
Primero con matrices:
</style>

In [9]:
import numpy as np

matriz1 = np.matrix(
    [[1, 4],
     [2, 0]]
)

2*matriz1

matrix([[2, 8],
        [4, 0]])

<span style="color:orange"> Ahora con arrays:</style> 

In [10]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

2*matriz1

array([[2, 8],
       [4, 0]])

## Multiplicación matricial

Si A es una matriz m × n, y si B es una matriz n × p con columnas b<sub>1</sub>, ... , b<sub>p</sub>, entonces el **producto** AB es la matriz m × p cuyas columnas son Ab<sub>1</sub>, ... , Ab<sub>p</sub>.
Esto es,
> AB = A [ b<sub>1</sub> b<sub>2</sub> ... b<sub>p</sub> ] = [ Ab<sub>1</sub> Ab<sub>2</sub> ... Ab<sub>p</sub> ]  
Más explícitamente:
A*B= $
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{m1} & a_{m2}  & ... & a_{mn}  \\
  \end{array} } \right]
$ * $
  \left[ {\begin{array}{cc}
   b_{11} & b_{12}  & ... & b_{1p}  \\
   b_{21} & b_{22}  & ... & b_{2p}  \\
   ... & ...  & ... & ...  \\
   b_{n1} & b_{n2}  & ... & b_{np}  \\
  \end{array} } \right]
$ = $
  \left[ {\begin{array}{cc}
   a_{11}\cdot b_{11}+ a_{12}\cdot b_{21} + ... + a_{1n}\cdot b_{n1}& a_{11}\cdot b_{12}+ a_{12}\cdot b_{22} + ... + a_{1n}\cdot b_{n2}  & ... & a_{11}\cdot b_{1p}+ a_{12}\cdot b_{2p} + ... + a_{1n}\cdot b_{np}  \\
   a_{21}\cdot b_{11}+ a_{22}\cdot b_{21} + ... + a_{2n}\cdot b_{n1}& a_{21}\cdot b_{12}+ a_{22}\cdot b_{22} + ... + a_{2n}\cdot b_{n2}  & ... & a_{21}\cdot b_{1p}+ a_{22}\cdot b_{2p} + ... + a_{2n}\cdot b_{np}  \\
   ... & ...  & ... & ...  \\
      a_{m1}\cdot b_{11}+ a_{m2}\cdot b_{21} + ... + a_{mn}\cdot b_{n1}& a_{m1}\cdot b_{12}+ a_{m2}\cdot b_{22} + ... + a_{mn}\cdot b_{n2}  & ... & a_{m1}\cdot b_{1p}+ a_{m2}\cdot b_{2p} + ... + a_{mn}\cdot b_{np}  \\
  \end{array} } \right]
$  

<span style="color:orange"> Ejemplo: Queremos multiplicar las matrices $
  matriz1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$ y $
  matriz2=
  \left[ {\begin{array}{cc}
   -1 & 2 \\
   1 & -2\\
  \end{array} } \right]
$.  
Primero con matrices:</style> 

In [11]:
import numpy as np

matriz1 = np.matrix(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.matrix(
    [[-1, 2],
     [1, -2]]
)

matriz1 * matriz2

matrix([[ 3, -6],
        [-2,  4]])

<span style="color:orange"> Ahora con arrays:</style> 

In [12]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.array(
    [[-1, 2],
     [1, -2]]
)

matriz1 * matriz2

array([[-1,  8],
       [ 2,  0]])

<span style="color:orange"> Si nos fijamos, no coincide con el anterior resultado. Aquí una diferencia entre trabajar con arrays y con matrices.  
El asterisco con arrays es multiplicación elemento aelemento. Si lo que queremos, como es el caso, es hacer la multiplicación matrical, tenemos que usar dot:</style> 

In [13]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.array(
    [[-1, 2],
     [1, -2]]
)

np.dot(matriz1,matriz2)

array([[ 3, -6],
       [-2,  4]])

#### Advertencias

* En general, AB ≠ BA.  

<span style="color:orange"> Ejemplo: Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   5 & 1 \\
   3 & -2\\
  \end{array} } \right]
$ y $
  B=
  \left[ {\begin{array}{cc}
   2 & 0 \\
   4 & 3\\
  \end{array} } \right]
$, queremos calcular AB y BA.</style> 

In [14]:
import numpy as np

matriz1 = np.matrix(
    [[5, 1],
     [3, -2]]
)

matriz2 = np.matrix(
    [[2, 0],
     [4, 3]]
)

matriz1 * matriz2

matrix([[14,  3],
        [-2, -6]])

In [15]:
import numpy as np

matriz1 = np.matrix(
    [[5, 1],
     [3, -2]]
)

matriz2 = np.matrix(
    [[2, 0],
     [4, 3]]
)

matriz2 * matriz1

matrix([[10,  2],
        [29, -2]])

* Si AB = AC, en general no es cierto que B = C.  

<span style="color:blue"> Ejemplo:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [7]:
import numpy as np

A = np.matrix([
    [2, -3],
    [-4, 6]
])

B = np.matrix([
    [8, 4],
    [5, 5]
])

C = np.matrix([
    [5, -2],
    [3, 1]
])

AB= A*B
AC = A * C
print(AB)
print(AC)

print("¿Es AB = AC?: {0}".format(np.array_equal(AB, AC)))

[[ 1 -7]
 [-2 14]]
[[ 1 -7]
 [-2 14]]
¿Es AB = AC?: True


In [8]:
print("¿Es B = C?: {0}".format(np.array_equal(B, C)))

¿Es B = C?: False


<span style="color:blue"> Ejemplo :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [6]:
import numpy as np

A = np.matrix(
    [[3, -6],
     [-1, 2]]
)

B = np.matrix(
    [[2, 6],
     [1, 3]]
)

A*B

matrix([[0, 0],
        [0, 0]])

## Traspuesta de una matriz

Dada una matriz A de m × n, la transpuesta de A es la matriz n × m, denotada mediante A<sup>T</sup>, cuyas columnas se forman a partir de las filas correspondientes de A.

<span style="color:orange"> Ejemplo: Dada la matriz $
  A=
  \left[ {\begin{array}{cc}
   5 & 1 & 7\\
   3 & -2 & 5\\
  \end{array} } \right]
$ , su matriz traspuesta es $
  A^T=
  \left[ {\begin{array}{cc}
   5 & 3 \\
   1 & -2\\
   7 & 5\\
  \end{array} } \right]
$.  
¿Cómo lo haríamos en Python?  
Primero con matrices:</style> 

In [18]:
import numpy as np
A=np.matrix([
   [5,1,7],
   [3,-2,5]
   ])
AT=np.transpose(A)
AT

matrix([[ 5,  3],
        [ 1, -2],
        [ 7,  5]])

<span style="color:orange"> Ahora con arrays:</style> 

In [19]:
import numpy as np
A=np.array([
   [5,1,7],
   [3,-2,5]
   ])
AT=np.transpose(A)
AT

array([[ 5,  3],
       [ 1, -2],
       [ 7,  5]])

## Un paréntesis necesario

**append vs vstack vs hstack**  
* numpy.vstack: agrupa los conjuntos en filas 
* numpy.hstack: apila matrices horizontalmente  
* append es una función en la que cada vez agrega un elemento a la lista



In [26]:
import numpy as np
np.vstack(([1,2,3],[4,5,6],[7,8,9]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
import numpy as np
np.hstack(([1,2,3],[4,5,6],[7,8,9]))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
import numpy as np
np.append([1,2,3],[4,5,6])

array([1, 2, 3, 4, 5, 6])

**¿Cómo agregar una nueva fila a una matriz numpy vacía?**  

Si usase el estándar de Python, podría hacer lo siguiente:

In [1]:
matriz=[]
matriz

[]

In [2]:
# añado la fila primera
matriz.append([1,2,3])
matriz

[[1, 2, 3]]

In [3]:
# Añado la segunda fila
matriz.append([4,5,6])
matriz

[[1, 2, 3], [4, 5, 6]]

Sin embargo, en Numpy tengo que tener cuidado:

In [6]:
import numpy as np
matriz=np.array([])
matriz
# Nos devuelve el tipo float

array([], dtype=float64)

In [28]:
# Para convertirlo a formato entero
import numpy as np
matriz=np.array([], dtype=int)
matriz

array([], dtype=int64)

In [29]:
matriz=np.append(matriz,np.array([1,2,3]))
matriz

array([1, 2, 3])

In [26]:
matriz=np.append(matriz,np.array([4,5,6]))
matriz
# No valdría. Lo está tratando como un array cualquiera

array([1, 2, 3, 4, 5, 6])

In [31]:
# Volvemos al estado anterior
import numpy as np
matriz=np.array([], dtype=int)
matriz
matriz=np.append(matriz,np.array([1,2,3]))
matriz
# Si le ponemos doble corchete, entonces sí que lo interpreta como matriz
matriz=np.append([matriz],[[4,5,6], [7,8,9]], axis=0)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si intentásemos hacerlo con vstack:

In [12]:
import numpy as np
matriz=np.vstack([])
matriz
# No se puede. ¿Entonces cómo lo hago?
# Hay varios modos. Por ejemplo, inicializarla con append y continuar con vstarck una vez haya al menos una fila

ValueError: need at least one array to concatenate

In [32]:
import numpy as np
matriz=np.array([])
matriz

array([], dtype=float64)

In [33]:
matriz=np.vstack(([1,2,3],[4,5,6],[7,8,9]))
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Matriz inversa (usando Gauss)

Al igual que el inverso de 5 es $\frac{1}{5}$ = 5<sup>-1</sup>, dada la matriz A, no puedo calcular $\frac{1}{A}$, pero sí A<sup>-1</sup>.  
La manera usual de calcular la matriz inversa, sobre todo si no es demasiado grande, es mediante determinantes (lo veremos posteriormente), pero hay otro modo general de calcular la matriz inversa, que es con el método de Gauss:  
* Dada una matriz A, considero la matriz (A|I)
* Mediante una serie de transformaciones tengo que conseguir transformarla en (I|B)
* B=A<sup>-1</sup>  

<span style="color:orange"> Ejemplo: Vamos a encontrar la inversa de  $
  A=
  \left[ {\begin{array}{cc}
   0 & 1 & 2\\
   1 & 0 & 3\\
   4 & -3 & 8\\
  \end{array} } \right]
$  usando el método de Gauss "a mano"</style> 

<span style="color:blue"> Ejemplo: Vamos a encontrar la inversa de  $
  A=
  \left[ {\begin{array}{cc}
   0 & 1 & 2\\
   1 & 0 & 3\\
   4 & -3 & 8\\
  \end{array} } \right]
$  usando el método de Gauss esta vez con Python</style> 

<span style="color:blue"> Vamos a considerar la matriz ampliada con la matriz identidad:  
$
  (A|I)=
  \left[ {\begin{array}{cc}
   0 & 1 & 2 & 1 & 0 & 0\\
   1 & 0 & 3 & 0 & 1 & 0\\
   4 & -3 & 8 & 0 & 0 & 1\\
  \end{array} } \right]
$  usando el método de Gauss</style> 

In [20]:
import numpy as np
A_I=np.array([
   [0,1,2,1,0,0],
   [1,0,3,0,1,0],
   [4,-3,8,0,0,1]
   ])
A_I

array([[ 0,  1,  2,  1,  0,  0],
       [ 1,  0,  3,  0,  1,  0],
       [ 4, -3,  8,  0,  0,  1]])

<span style="color:blue"> Buscamos hacer transformaciones de modo que obtengamos una matriz de la pinta ( I | matriz).  
Lo primero que hacemos es intercambiar la segunda fila con la primera fla</style>   

<span style="color:blue"> Vamos a considerar la matriz ampliada con la matriz identidad:  
$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 3 & 0 & 1 & 0\\
   0 & 1 & 2 & 1 & 0 & 0\\
   4 & -3 & 8 & 0 & 0 & 1\\
  \end{array} } \right]
$  usando el método de Gauss</style> 

In [21]:
A_I_paso1=(
    A_I[1],A_I[0],A_I[2])
A_I_paso1

(array([1, 0, 3, 0, 1, 0]),
 array([0, 1, 2, 1, 0, 0]),
 array([ 4, -3,  8,  0,  0,  1]))

<span style="color:blue"> OJO! Se ha convertido en un array de arrays, pero nosotros queremos un único array.  
Veamos cómo hacerlo.</style> 

In [22]:
# Añadimos al array la primera y la segunda fila
A_I_paso1=np.append([A_I[1]],[A_I[0]],0)
A_I_paso1

array([[1, 0, 3, 0, 1, 0],
       [0, 1, 2, 1, 0, 0]])

In [23]:
# Añadimos a nuestra "temporal" A_I_paso1 la tercera fila
A_I_paso1=np.vstack([A_I_paso1,[A_I[2]]])
A_I_paso1

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 4, -3,  8,  0,  0,  1]])

<span style="color:blue"> Queremos hacer 0 el elemento de la posición 31 (20 para Python).  
Para ello la tercera fila se convertirá en el resultado de multiplicar -4 por la primera fila y sumarle la tercera fila. A partir de ahora, este tipo de operaciones lo expresaremos como (III) = -4(I)+(III):</style>  

<span style="color:blue">$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 3 & 0 & 1 & 0\\
   0 & 1 & 2 & 1 & 0 & 0\\
   0 & -3 & -4 & 0 & -4 & 1\\
  \end{array} } \right]
$ </style> 

In [24]:
# Creamos la A_I_paso2 con las filas 1 y 2 de la matriz A_I_paso1
A_I_paso2=np.append([A_I_paso1[0]],[A_I_paso1[1]],0)
A_I_paso2

array([[1, 0, 3, 0, 1, 0],
       [0, 1, 2, 1, 0, 0]])

In [25]:
# Añadimos a nuestra "temporal" A_I_paso2 la tercera fila "transformada"
A_I_paso2=np.vstack([A_I_paso2,[A_I_paso1[2]-4*A_I_paso1[0]]])
A_I_paso2

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 0, -3, -4,  0, -4,  1]])

<span style="color:blue"> Queremos hacer 0 el elemento de la posición 32 (21 para Python).</style>  

<span style="color:blue"> Para ello haremos (III)=3 (II) + (III)</style>  

<span style="color:blue">$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 3 & 0 & 1 & 0\\
   0 & 1 & 2 & 1 & 0 & 0\\
   0 & 0 & 2 & 3 & -4 & 1\\
  \end{array} } \right]
$ </style> 

In [26]:
# Creamos la A_I_paso3 con las filas 1 y 2 de la matriz A_I_paso2
A_I_paso3=np.append([A_I_paso2[0]],[A_I_paso2[1]],0)
A_I_paso3

array([[1, 0, 3, 0, 1, 0],
       [0, 1, 2, 1, 0, 0]])

In [27]:
# Añadimos a nuestra "temporal" A_I_paso3 la tercera fila "transformada"
A_I_paso3=np.vstack([A_I_paso3,[A_I_paso2[2]+3*A_I_paso2[1]]])
A_I_paso3

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 0,  0,  2,  3, -4,  1]])

<span style="color:blue"> Queremos hacer 0 el elemento de la posición 13 (02 para Python).</style> 

<span style="color:blue"> Para ello haremos (I)=(I) - 3/2 * (III)</style>  

<span style="color:blue">$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 2 & 1 & 0 & 0\\
   0 & 0 & 2 & 3 & -4 & 1\\
  \end{array} } \right]
$ </style> 

In [28]:
# Creamos la A_I_paso4 con la filas 1 transformada
A_I_paso4=np.array([A_I_paso3[0]-(3/2)*A_I_paso3[2]])
A_I_paso4

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5]])

In [29]:
# Añadimos a nuestra "temporal" A_I_paso4 la segunda fila
A_I_paso4=np.vstack([A_I_paso4,[A_I_paso3[1]]])
A_I_paso4

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ]])

In [30]:
# Añadimos a nuestra "temporal" A_I_paso4 la tercera fila
A_I_paso4=np.vstack([A_I_paso4,[A_I_paso3[2]]])
A_I_paso4

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  2. ,  3. , -4. ,  1. ]])

<span style="color:blue"> Queremos hacer 0 el elemento de la posición 23 (02 para Python).</style>  

<span style="color:blue"> Para ello haremos (II)=(II) - (III)</style>  

<span style="color:blue">$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 0 & -2 & 4 & -1\\
   0 & 0 & 2 & 3 & -4 & 1\\
  \end{array} } \right]
$ </style> 

In [31]:
# Creamos la A_I_paso5 con las filas 1 y la 2 transformada
A_I_paso5=np.append([A_I_paso4[0]],[A_I_paso4[1]-A_I_paso4[2]],0)
A_I_paso5

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ]])

In [32]:
# Añadimos a nuestra "temporal" A_I_paso5 la tercera fila
A_I_paso5=np.vstack([A_I_paso5,[A_I_paso4[2]]])
A_I_paso5

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  2. ,  3. , -4. ,  1. ]])

<span style="color:blue"> Queremos hacer 1 el elemento de la posición 33 (02 para Python).</style>  

<span style="color:blue"> Para ello haremos (III)=(1/2) * (III)</style>  

<span style="color:blue">$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 0 & -2 & 4 & -1\\
   0 & 0 & 1 & 3/2 & -2 & 1/2\\
  \end{array} } \right]
$ </style> 

In [33]:
# Creamos la A_I_paso6 con las filas 1 y 2
A_I_paso6=np.append([A_I_paso5[0]],[A_I_paso5[1]],0)
A_I_paso6

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ]])

In [34]:
# Añadimos a nuestra "temporal" A_I_paso6 la tercera fila transformada
A_I_paso6=np.vstack([A_I_paso6,[(1/2)*A_I_paso5[2]]])
A_I_paso6

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

<span style="color:blue"> Luego la matriz inversa queda:</style> 
<span style="color:blue">$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 0 & -2 & 4 & -1\\
   0 & 0 & 1 & 3/2 & -2 & 1/2\\
  \end{array} } \right]
$ </style> 

In [35]:
#Para sacarlo en Python hay que hacerlo un poquito especial
inv_A=np.transpose(np.vstack([A_I_paso6[:,3],A_I_paso6[:,4],A_I_paso6[:,5]]))
inv_A

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])


Sorpresa! Se puede hacer directamente:

In [36]:
import numpy as np
A=np.matrix([
   [0,1,2],
   [1,0,3],
   [4,-3,8]
   ])

inv_A = np.linalg.inv(A)
inv_A

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [37]:
import numpy as np
A=np.array([
   [0,1,2],
   [1,0,3],
   [4,-3,8]
   ])

inv_A = np.linalg.inv(A)
inv_A

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

## Rango de una matriz

El rango de una matriz se define como el número de vectores linealmente independientes que la componen.  
Siempre va a ser menor o igual que el menor de las cantidades número_filas y número_columnas.  

<span style="color:blue"> Ejemplo: Vamos a calcular el rango de  $
  A=
  \left[ {\begin{array}{cc}
   2 & 5 & -3 & -4 & 8\\
   4 & 7 & -4 & -3 & 9\\
   6 & 9 & -5 & 2 & 4\\
   60 & -9 & 6 & 5 & -6\\
  \end{array} } \right]
$ usando Gauss </style> 


In [38]:
import numpy as np
A=np.matrix([
   [2,5,-3,-4,8],
   [4,7,-4,-3,9],
   [6,9,-5,2,4],
   [60,-9,6,5,-6]
   ])
A

matrix([[ 2,  5, -3, -4,  8],
        [ 4,  7, -4, -3,  9],
        [ 6,  9, -5,  2,  4],
        [60, -9,  6,  5, -6]])

<span style="color:blue"> Queremos hacer 0 los elementos de la primera columna salvo el de la primera fila.</style> 

In [39]:
A_paso1=np.vstack([A[0],A[1]-2*A[0]])
A_paso1

matrix([[ 2,  5, -3, -4,  8],
        [ 0, -3,  2,  5, -7]])

In [40]:
A_paso1=np.vstack([A_paso1,A[2]-3*A[0]])
A_paso1

matrix([[  2,   5,  -3,  -4,   8],
        [  0,  -3,   2,   5,  -7],
        [  0,  -6,   4,  14, -20]])

In [41]:
A_paso1=np.vstack([A_paso1,A[3]-10*A[2]])
A_paso1

matrix([[  2,   5,  -3,  -4,   8],
        [  0,  -3,   2,   5,  -7],
        [  0,  -6,   4,  14, -20],
        [  0, -99,  56, -15, -46]])

<span style="color:blue"> Queremos hacer 0 los elementos de la segunda columna exceptuando las dos primeras filas.</style>

In [42]:
A_paso2=np.vstack([A_paso1[0],A_paso1[1]])
A_paso2

matrix([[ 2,  5, -3, -4,  8],
        [ 0, -3,  2,  5, -7]])

In [43]:
A_paso2=np.vstack([A_paso2,A_paso1[2]-2*A_paso1[1]])
A_paso2

matrix([[ 2,  5, -3, -4,  8],
        [ 0, -3,  2,  5, -7],
        [ 0,  0,  0,  4, -6]])

In [44]:
A_paso2=np.vstack([A_paso2,A_paso1[3]-33*A_paso1[1]])
A_paso2

matrix([[   2,    5,   -3,   -4,    8],
        [   0,   -3,    2,    5,   -7],
        [   0,    0,    0,    4,   -6],
        [   0,    0,  -10, -180,  185]])

<span style="color:blue"> Queremos hacer 0 el elemento 43.  
Si intercambio la fila 3 con la 4 ya lo tendría:</style>

In [45]:
A_paso3=np.vstack([A_paso2[0],A_paso2[1]])
A_paso3=np.vstack([A_paso3,A_paso2[3]])
A_paso3=np.vstack([A_paso3,A_paso2[2]])
A_paso3

matrix([[   2,    5,   -3,   -4,    8],
        [   0,   -3,    2,    5,   -7],
        [   0,    0,  -10, -180,  185],
        [   0,    0,    0,    4,   -6]])

<span style="color:blue"> Luego RangoA=4.</style>  

¿Alguna manera directa desde Python?

In [7]:
import numpy as np
A=np.matrix([
   [2,5,-3,-4,8],
   [4,7,-4,-3,9],
   [6,9,-5,2,4],
   [60,-9,6,5,-6]
   ])
np.linalg.matrix_rank(A)

4

Para una matriz M, el **rango por filas** de M es el rango de sus filas y el **rango por columnas** de M es el rango de sus columnas.  

<span style="color:blue"> Ejemplo:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0   \\
   0 & 2  & 0   \\
   2 & 4  & 0   \\
  \end{array} } \right]
$
Las filas de M son los vectores [1, 0, 0], [0, 2, 0], [2, 4, 0]. El conjunto formado por estos vectores {[1, 0, 0], [0, 2, 0], [2, 4, 0]} tiene rango dos, por lo que el rango por filas de M es 2.  
Las columnas de M son [1, 0, 2], [0, 2, 4], [0, 0, 0]. Como el tercer vector es el vector cero, no es necesario calcular el espacio vectorial generado por los tres vectores. Basta con observar que los dos primeros vectores tienen alguna coordenada 0 pero en diferentes posiciones, luego ambos son linalmente independientes. Por tanto, el rango por columnas es dos.  
¿Cómo lo podemos calcular en Python?</style>

In [1]:
import numpy as np
M=np.matrix([
    [1,0,0],
    [0,2,0],
    [2,4,0]
])
rangoM=np.linalg.matrix_rank(M)
rangoM

2

<span style="color:blue"> Ejemplo:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$  
Cada una de las filas tiene un valor distinto de cero donde las demás tienen ceros, por lo que las tres filas son linealmente independientes. Por lo tanto, el rango por filas de M es tres.
Las columnas de M son [1,0,0], [0,2,0], [0,0,3] y [5,7,9].
Las tres primeras columnas son linealmente independientes, y la cuarta puede escribirse como una combinación lineal de las tres primeras, por lo que el rango de columna es tres.</style>  

In [34]:
import numpy as np
M=np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
rangoM=np.linalg.matrix_rank(M)
rangoM

3

## Eliminación gaussiana

Aunque ya hemos visto algunos casos de uso "algebraico", comentemos algunas utilidades importantes que tiene la eliminación gaussiana:  

* Encontrar una base para el espacio generador dados ciertos vectores. Esto también nos proporciona un algoritmo para el rango y, por lo tanto, para probar la dependencia lineal.  
* Resolver una ecuación matricial, que es lo mismo que expresar un vector dado como una combinación lineal de otros vectores dados, que es lo mismo que resolver un sistema de ecuaciones lineales.  
* Encontrar una base para el espacio nulo de una matriz, que es lo mismo que encontrar una base para el conjunto de soluciones de un sistema lineal homogéneo, que también es importante para representar el conjunto de soluciones de un sistema lineal general.  


## Forma escalonada  

La **forma escalonada** es la generalización de las matrices triangulares.  

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 2  & 3 & 0 & 5 & 6 \\
   0 & 1  & 1 & 0 & 3 & 4 \\
   0 & 0  & 1 & 0 & 1 & 2 \\
   0 & 0  & 0 & 1 & 0 & 6 \\
  \end{array} } \right]
$ está en forma escalonada.  
Fijemonos en:</style>  
* <span style="color:orange"> La primera entrada distinta de cero en la fila 1 está en la columna 1.</style>   
* <span style="color:orange"> La primera entrada distinta de cero en la fila 2 está en la columna 2.</style>   
* <span style="color:orange"> La primera entrada distinta de cero en la fila 3 está en la columna 3.</style>     
<span style="color:orange"> La primera entrada distinta de cero en la fila 4 está en la columna 4.</style>   

<span style="color:orange"> Un poco más retorcido:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 2  & 3 & 0 & 5 & 6 \\
   0 & 1  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 1 & 2 \\
   0 & 0  & 0  & 0 & 0 & 6 \\
  \end{array} } \right]
$ está en forma escalonada.  
Fijemonos en:</style>  
* <span style="color:orange"> La primera entrada distinta de cero en la fila 1 está en la columna 1.</style>   
* <span style="color:orange"> La primera entrada distinta de cero en la fila 2 está en la columna 2.</style>   
* <span style="color:orange"> La primera entrada distinta de cero en la fila 3 está en la columna 5.</style>     * <span style="color:orange"> La primera entrada distinta de cero en la fila 4 está en la columna 6.</style>   

Una matriz A mxn está en **forma escalonada** si cumple la siguiente condición:  
para cualquier fila, si la primera entrada distinta de cero de esa fila está en la posición k, la primera entrada distinta de cero de cada fila anterior está en una posición menor que k.  

Esta definición implica que, a medida que recorre las filas de A, las primeras entradas distintas de cero se mueven estrictamente a la derecha, formando una especie de escalera que desciende a la derecha. 

Dicho de otro modo, una matriz está escalonada si:
* El primer elemento de la matriz, a<sub>11</sub>, debe ser distinto de cero.  
* El primer elemento diferente de 0 de cada fila esta a la derecha del primer elemento diferente de 0 de la fila anterior.  
* Todas filas cero están en la parte inferior de la matriz.

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   4 & 1  & 3 & 0  \\
   0 & 3  & 0 & 1  \\
   0 & 0  & 1 & 7  \\
   0 & 0 & 0  & 9  \\
  \end{array} } \right]
$ está en forma escalonada.  </style>  

Si una fila de una matriz en forma escalonada es cero, cada fila subsiguiente también debe ser cero.  

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 0 & 0 \\
   0 & 0 & 0  & 0 & 0 & 0 \\
  \end{array} } \right]
$ NO está en forma escalonada.  </style>  

Una **matriz Escalonada Reducida por Filas** es aquella matriz en las que los pivotes son los únicos elementos no nulos de cada fila. 

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0  \\
   0 & 1  & 0  \\
   0 & 0  & 1  \\
   0 & 0  & 0  \\
  \end{array} } \right]
$ está en forma escalonada reducida por filas.  </style> 

¿De qué sirve tener una matriz en forma escalonada?  
Si una matriz está en forma escalonada, las filas distintas de cero forman una base para el espacio vectorial formado por las "filas".  

<span style="color:orange"> Ejemplo:  
Una base para el espacio filas de $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 0 & 0 \\
   0 & 0 & 0  & 0 & 0 & 0 \\
  \end{array} } \right]
$ es {[0,2,3,0,5,6],[0,1,0,3,4]}.</style>  

<span style="color:orange"> Ejemplo:  
Si todas las filas son diferentes de cero, como en $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 1 & 2 \\
   0 & 0 & 0  & 0 & 0 & 6 \\
  \end{array} } \right]
$, el espacio filas estará formado por todas las filas.</style>  

Si la matriz está en forma escalonada, las filas distintas de cero forman una base para el espacio vectorial "filas". 

## Algoritmo para transformar una matriz en una matriz escalonada  

Es algo complicado y desde luego mejorable continuamente. ¡Se admiten sugerencias!

In [88]:
import numpy as np

A = np.matrix([
    [5,8,9],
    [0,6,7],
    [1,2,3]
])

def escalonar(M):
    # Tenemos que hacer 0´s. Recordemos que lo hacemos por columnas
    # Empecemos por la columna 0:
    i=0
    # Si el elemento que está es la posición (0,0) es diferente de 0, estaría perfecto:
    if M[i,i]!=0:
        M[i,i]=M[i,i]    
    return M

escalonar(A)

# ¿Qué ocurre si el primer elemento es 0? 
# Tenemos que buscas una fila en la que ese elemento no sea 0

matrix([[5, 8, 9],
        [0, 6, 7],
        [1, 2, 3]])

In [90]:
#Copiamos del anterior
import numpy as np
# Ponemos un 0 en la posicón (0,0)
B = np.matrix([
    [0,8,9],
    [0,6,7],
    [1,2,3]
])

def escalonar(M):
    i=0
    if M[i,i]!=0:
        M[i,i]=M[i,i]
    #Cuando el elemento es 0
    if M[i,i]==0:
        print("El elemento ({0},{0}) vale 0. Busco intercambiar esa fila por una posterior".format(i))
        # Hacemos un for que mire desde la posicion 1 hasta el final de la columna
        # shape devuelve el rango (filas, columnas)
        for l in range(i+1,M.shape[0]):
            # En range el ultimo valor no esta incluido: 
            # como i es 0, cogera los valores 1 y 2 (lo que queremos)
            if M[l, i] !=0:
                print("El elemento ({0},{1}) vale distinto de 0. La fila {0} es la que quiero intercambiar".format(l,i))
                # Me "guardo" la fila 0
                temp = M[i, :].copy()
                # Copio la fila encontrada en la fila 0
                M[i,:] = M[l,:]
                # Sustituyo la fila encontrada por la fila 0
                M[l,:] = temp
    return M

escalonar(B)
# Vale, funciona
# Realmente el primer if (M[i,i]!=0) no haría falta, así que a partir de ahora lo quitamos

El elemento (0,0) vale 0. Busco intercambiar esa fila por una posterior
El elemento (2,0) vale distinto de 0. La fila 2 es la que quiero intercambiar


matrix([[1, 2, 3],
        [0, 6, 7],
        [0, 8, 9]])

In [91]:
# Volvamos con la matriz A

import numpy as np

A = np.matrix([
    [5,8,9],
    [0,6,7],
    [1,2,3]
])

def escalonar(M):
    i=0
    if M[i,i]==0:
        print("El elemento ({0},{0}) vale 0. Busco intercambiar esa fila por una posterior".format(i))
        for l in range(i+1,M.shape[0]):
            if M[l, i] !=0:
                print("El elemento ({0},{1}) vale distinto de 0. La fila {0} es la que quiero intercambiar".format(l,i))
                temp = M[i, :].copy()
                M[i,:] = M[l,:]
                M[l,:] = temp
    # Para los elementos en la posicion (loquesea,0), que estén por debajo de la fila 0, 
    # es decir, desde la fila 1, queremos hacerlos cero.
    for j in range(i+1,M.shape[0]):
        if M[j,i] ==0:
            print("Dejamos la fila {0} como esta".format(j))
            M[j,:]=M[j,:]
        if M[j,i] !=0: 
            print("Veremos ahora cómo tratar la fila {0}".format(j))
    return M

escalonar(A)



Dejamos la fila 1 como esta
Veremos ahora cómo tratar la fila 2


matrix([[5, 8, 9],
        [0, 6, 7],
        [1, 2, 3]])

In [92]:
import numpy as np

A = np.matrix([
    [5,8,9],
    [0,6,7],
    [1,2,3]
])

def escalonar(M):
    i=0
    if M[i,i]==0:
        print("El elemento ({0},{0}) vale 0. Busco intercambiar esa fila por una posterior".format(i))
        for l in range(i+1,M.shape[0]):
            if M[l, i] !=0:
                print("El elemento ({0},{1}) vale distinto de 0. La fila {0} es la que quiero intercambiar".format(l,i))
                temp = M[i, :].copy()
                M[i,:] = M[l,:]
                M[l,:] = temp
    for j in range(i+1,M.shape[0]):
        if M[j,i] ==0:
            M[j,:]=M[j,:]
        if M[j,i] !=0: 
            # Para que valga siempre, tengo que hacer 0 usando la primera fila
            # Multiplicamos la fila cero por el valor en la posicion (2,0)
            # y la segunda fila por el valor de la posicion (0,0)
            # Ahora cuidado:
            # Si el valor (0,0) es negativo y el (2,0) positivo los sumaría o al revés también
            # Pero si los dos son negativos o los dos positivos, necesito cambiar el signo a uno de ellos
            if M[i,i]>0:
                M[j,:]=M[j,i]*M[i,:]-M[i,i]*M[j,:]
            if M[i,i]<0:
                if M[j,i]>0:
                    M[j,:]=M[j,i]*M[i,:]+M[i,i]*M[j,:]
                if M[j,i]<0:
                    M[j,:]=M[j,i]*M[i,:]-M[i,i]*M[j,:]
    return M

escalonar(A)

matrix([[ 5,  8,  9],
        [ 0,  6,  7],
        [ 0, -2, -6]])

In [93]:
# Veamos que funciona en todas las combinaciones

import numpy as np

C = np.matrix([
    [5,8,9],
    [0,6,7],
    [-1,2,3]
])

escalonar(C)

matrix([[  5,   8,   9],
        [  0,   6,   7],
        [  0, -18, -24]])

In [94]:
import numpy as np

D = np.matrix([
    [-5,8,9],
    [0,6,7],
    [1,2,3]
])

escalonar(D)

matrix([[  -5,    8,    9],
        [   0,    6,    7],
        [   0,  -90, -120]])

In [95]:
import numpy as np

E = np.matrix([
    [-5,8,9],
    [0,6,7],
    [-1,2,3]
])

escalonar(E)

matrix([[-5,  8,  9],
        [ 0,  6,  7],
        [ 0,  2,  6]])

In [98]:
#Habíamos fijado la primera columna
# Ahora uqeremos recorrer todas las columnas
import numpy as np

A = np.matrix([
    [5,8,9],
    [0,6,7],
    [1,2,3]
])

def escalonar(M):
    # El rango lo miramos con respecto al numero de columnas
    for i in range(0, M.shape[1]-1):
        if M[i,i]!=0:
            M[i,i]=M[i,i]
        if M[i,i]==0:
            for l in range(i+1,M.shape[0]):
                if M[l, i] !=0:
                    temp = M[i, :].copy()
                    M[i,:] = M[l,:]
                    M[l,:] = temp
        for j in range(i+1,M.shape[0]):
            if M[j,i] ==0:
                M[j,:]=M[j,:]
            if M[j,i] !=0: 
                if M[i,i]>0:
                    M[j,:]=M[j,i]*M[i,:]-M[i,i]*M[j,:]
                if M[i,i]<0:
                    if M[j,i]>0:
                        M[j,:]=M[j,i]*M[i,:]+M[i,i]*M[j,:]
                    if M[j,i]<0:
                        M[j,:]=M[j,i]*M[i,:]-M[i,i]*M[j,:]
    return M

escalonar(A)

matrix([[ 5,  8,  9],
        [ 0,  6,  7],
        [ 0,  0, 22]])

In [99]:
# ¿Funcionaría también si el número de filas es mayor que el de columnas?

import numpy as np

F = np.matrix([
    [1,2,3],
    [3,4,5],
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

escalonar(F)

matrix([[1, 2, 3],
        [0, 2, 4],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [100]:
# ¿Y si el numero de columnas es mayor que el de filas?

import numpy as np

G = np.matrix([
    [1,2,3,4,5,6,7],
    [3,4,5,6,7,4,2],
    [1,2,3,4,5,6,7],
    [1,2,3,4,5,6,7],
    [1,2,3,4,5,6,7]
])

escalonar(G)
# No funciona porque la variable i es grande y al hacer los for, 
# los valores que va encontrando, los elementos que busca, no los encuentra

IndexError: index 5 is out of bounds for axis 0 with size 5

In [129]:
import numpy as np

A = np.matrix([
    [5,8,9],
    [0,6,7],
    [1,2,3]
])

def escalonar(M):
    # El rango lo miramos con respecto al minimo entre el numero de filas y de columnas
    for i in range(0, min(M.shape[0],M.shape[1])-1):
        if M[i,i]!=0:
            M[i,i]=M[i,i]
        if M[i,i]==0:
            for l in range(i+1,M.shape[0]):
                if M[l, i] !=0:
                    temp = M[i, :].copy()
                    M[i,:] = M[l,:]
                    M[l,:] = temp
        for j in range(i+1,M.shape[0]):
            if M[j,i] ==0:
                M[j,:]=M[j,:]
            if M[j,i] !=0: 
                if M[i,i]>0:
                    M[j,:]=M[j,i]*M[i,:]-M[i,i]*M[j,:]
                if M[i,i]<0:
                    if M[j,i]>0:
                        M[j,:]=M[j,i]*M[i,:]+M[i,i]*M[j,:]
                    if M[j,i]<0:
                        M[j,:]=M[j,i]*M[i,:]-M[i,i]*M[j,:]
    return M

escalonar(A)

matrix([[ 5,  8,  9],
        [ 0,  6,  7],
        [ 0,  0, 22]])

In [131]:
import numpy as np

G = np.matrix([
    [1,2,3,4,5,6,7],
    [3,4,5,6,7,4,2],
    [2,3,4,6,9,3,1],
    [5,8,2,5,3,1,0],
    [1,2,3,4,5,6,7]
])

escalonar(G)

matrix([[  1,   2,   3,   4,   5,   6,   7],
        [  0,   2,   4,   6,   8,  14,  19],
        [  0,   0, -18, -18, -28, -30, -32],
        [  0,   0,   0,   2,   6,  -4,  -7],
        [  0,   0,   0,   0,   0,   0,   0]])

In [132]:
import numpy as np

F = np.matrix([
    [1,2,3],
    [3,4,5],
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

escalonar(F)

matrix([[1, 2, 3],
        [0, 2, 4],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

## Factorización LU (Lower-Upper)

Sea A una matriz tenemos:  
> A = LU  

donde L y U son matrices inferiores y superiores triangulares respectivamente.  

Si pensamos en una matriz cuadrada:  
$
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{n1} & a_{n2}  & ... & a_{nn}  \\
  \end{array} } \right]
$ =
$
  \left[ {\begin{array}{cc}
   1      & 0       & 0    & ... & 0  \\
   l_{21} & 1       & 0    & ... & 0  \\
   ...    & ...     & ...  & ... & ... \\
   l_{n1} & l_{n2}  & ...  & ... & 1  \\
  \end{array} } \right]
$* $
  \left[ {\begin{array}{cc}
   u_{11} & u_{12} & u_{13} & ... & u_{1n}  \\
   0      & u_{22} & u_{23} & ... & b_{2n}  \\
   ...    & ...    & ...    & ... & ...     \\
   0      & 0      & ...    & ... & u_{nn}  \\
  \end{array} } \right]
$
  
Si la matriz A es invertible, es decir, tiene inversa, las matrices L y U son únicas.  

¿Qué utilidad tiene?   
* Resolución de sistemas de ecuaciones  
* Cálculo de la matriz inversa: A<sup>-1</sup>=U<sup>-1</sup> L<sup>-1</sup>  



<span style="color:orange"> Ejemplo:  
$\left[ {\begin{array}{cc}
   2 & 1 & 1\\
   1 & 2 & 1\\
   1 & 1 & 2\\
  \end{array} } \right] = \left[ {\begin{array}{cc}
   1 & 0 & 0\\
   \frac{1}{2} & 1 & 0\\
   \frac{1}{2} & \frac{1}{3} & 1\\
  \end{array} } \right] \left[ {\begin{array}{cc}
   2 & 1 & 1\\
   0 & \frac{3}{2} & \frac{1}{2}\\
   0 & 0 & \frac{4}{3}\\
  \end{array} } \right]$  
  Con Scipy:</style>

In [107]:
from numpy import matrix
from scipy import linalg
A=matrix([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
p, l,u=linalg.lu(A)
# p es la matriz de permutaciones. 
# Guarda algo así como los movimientos de filas que se hacen en el proceso de sacar L y U
p

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
l

array([[1.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        ],
       [0.5       , 0.33333333, 1.        ]])

In [109]:
u

array([[2.        , 1.        , 1.        ],
       [0.        , 1.5       , 0.5       ],
       [0.        , 0.        , 1.33333333]])

<span style="color:orange"> Con Sympy:</style>

In [110]:
from sympy import Matrix
A=Matrix([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
l,u,p=A.LUdecomposition()
l

Matrix([
[  1,   0, 0],
[1/2,   1, 0],
[1/2, 1/3, 1]])

In [111]:
u

Matrix([
[2,   1,   1],
[0, 3/2, 1/2],
[0,   0, 4/3]])

### Pasos para descomponer un sistema de ecuaciones utilizando la factorización LU

1. Obtener la matriz triangular inferior L y la matriz triangular superior U.  
2. Resolver Ly = b (para encontrar y).  
3. El resultado del paso anterior se guarda en una matriz nueva de nombre "y".  
4. Realizar Ux = y (para encontrar x).  
5. El resultado del paso anterior se almacena en una matriz nueva llamada "x", la cual da los valores correspondientes a las incógnitas de la ecuación.  

<span style="color:orange">Vamos a encontrar las soluciones del sistema (usando la factorización LU):</style>  
> <span style="color:orange">$\left\{
	       \begin{array}{ll}
               4x-2y-z=9  \\
               5x+y-z=7   \\
               x+2y-4z=12
	       \end{array}
	     \right.$</style>  

<span style="color:orange">Este sistema puede ser escrito como:</style>     
> <span style="color:orange">$\left(
\begin{array}{ccc|c}
4 & -2 & -1 & 9 \\
5 & 1  & -1 & 7 \\
1 & 2  & -4 & 12\\
\end{array}
\right)$</style>  

<span style="color:orange">donde: </style>    
> <span style="color:orange">A= $\left(
\begin{array}{ll}
4 & -2 & -1 \\
5 & 1  & -1 \\
1 & 2  & -4 \\
\end{array}
\right)$</style>  

<span style="color:orange">y B es igual a:  </style>  
> <span style="color:orange">B= $\left(
\begin{array}{ll}
9 \\
7 \\
12\\
\end{array}
\right)$</style> 

<span style="color:orange">Primero calculamos las matrices L y U</style>  


In [3]:
from sympy import Matrix
A=Matrix([
    [4,-2,-1],
    [5,1,-1],
    [1,2,-4]
])
l,u,p=A.LUdecomposition()
l

Matrix([
[  1,   0, 0],
[5/4,   1, 0],
[1/4, 5/7, 1]])

In [4]:
u

Matrix([
[4,  -2,     -1],
[0, 7/2,    1/4],
[0,   0, -55/14]])

<span style="color:orange">Ahora tenemos que resolver Ly=b y guardarlo en la variable Y:</style>  

In [5]:
import sympy as sp
import numpy as np

L=l

B = np.matrix([
    [9],
    [7],
    [12]
])

# Para no aplanar el resultado, le ponemos axis=1
L_B=np.append(L,B, axis=1)
L_B



matrix([[1, 0, 0, 9],
        [5/4, 1, 0, 7],
        [1/4, 5/7, 1, 12]], dtype=object)

In [15]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z

# Lo pasamos a objeto de sympy
L_B=Matrix(L_B)

Y=solve_linear_system(L_B,x,y,z)
Y



{x: 9, y: -17/4, z: 179/14}

<span style="color:orange">Ahora tenemos que resolver Ux=y y guardarlo en la variable X:</style>  

In [16]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z

U=u

Y=Matrix([
    [9],
    [-17/4],
    [179/14]
])
Y

U_Y=np.append(U,Y, axis=1)
U_Y

array([[4, -2, -1, 9],
       [0, 7/2, 1/4, -4.25000000000000],
       [0, 0, -55/14, 12.7857142857143]], dtype=object)

In [17]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z

U_Y=Matrix(U_Y)

X=solve_linear_system(U_Y,x,y,z)
X
# Y tendríamos la solución del sistema

{x: 0.945454545454545, y: -0.981818181818182, z: -3.25454545454545}

## Cambio de base en espacios vectoriales 

Recuperamos algo pendiente de los espacios vectoriales.

Recordemos que:  
Decimos que S es una **base** de vectores del espacio vectorial E si los vectores de S son linealmente independientes y generadores del espacio vectorial E.  

La idea es que queremos construir una matriz que nos permita cambiar las coordenadas de un vector en una base por las coordenadas del mismo vector en otra base.  

Dados a<sub>1</sub>,...,a<sub>n</sub> una base para V y b<sub>1</sub>,...,b<sub>k</sub> otra base para V.  

Queremos una matriz que nos mapee un vector cualquiera en la base b<sub>1</sub>,...,b<sub>k</sub> y lo convierte en un vector en la base a<sub>1</sub>,...,a<sub>n</sub>.  

Para ello, calculamos la matriz B a partir de los vectores b<sub>1</sub>,...,b<sub>k</sub> y A a partir de los vectores a<sub>1</sub>,...,a<sub>n</sub>.

Calculamos la **matriz de cambio de base** C como:  
> C=A<sup>-1</sup>*B   

Esta matriz mapea un vector en la base b<sub>1</sub>,...,b<sub>k</sub> y lo convierte en un vector en la base a<sub>1</sub>,...,a<sub>n</sub>.  

<span style="color:orange"> Ejemplo:  
Calcula la matriz de cambio de base de la base [1,2,3],[2,1,0],[0,1,4] a la base [2,0,1],[0,1,−1],[1,2,0].</style> 

In [18]:
# Queremos cambiar de la base B = {[1,2,3],[2,1,0],[0,1,4]} a la base A={[2,0,1],[0,1,−1],[1,2,0]}
import numpy as np

# Escribimos la matriz B en columnas
B=np.matrix([
    [1,2,0],
    [2,1,1],
    [3,0,4]
])

# Escribimos la matriz A en columnas
A=np.matrix([
    [2,0,1],
    [0,1,2],
    [1,-1,0]
])

inv_A=np.linalg.inv(A)

matriz_cambio=inv_A*B
matriz_cambio

matrix([[-1.        ,  1.        , -1.66666667],
        [-4.        ,  1.        , -5.66666667],
        [ 3.        ,  0.        ,  3.33333333]])

<span style="color:orange"> Queremos convertir el vector [1,2,3] a la base [2,0,1],[0,1,−1],[1,2,0].</style> 

In [223]:
import numpy as np
V=np.matrix([
    [1],
    [2],
    [3]
])

matriz_cambio*V

matrix([[ -4.],
        [-19.],
        [ 13.]])

En la vida real, el cambio de base se utiliza para muchas cosas, entre ellas, para eliminar la perspectiva de una imagen.

<img src="Images/perspective_1.png" style="width: 300px;"/> 
<img src="Images/perspective_1a.png" style="width: 300px;"/> 