# 9. Sistemas de ecuaciones

## ¿Qué es un sistema de ecuaciones lineales?  

Dados a<sub>ij</sub>, b<sub>i</sub> escalares, un sistema de ecuaciones lineales con *n* incógnitas:
> $a_{11}\cdot x_1+a_{12}\cdot x_2+...+a_{1n}\cdot x_n=b_1$  
> $a_{21}\cdot x_1+a_{22}\cdot x_2+...+a_{1n}\cdot x_n=b_2$  
> ...  
> $a_{m1}\cdot x_1+a_{m2}\cdot x_2+...+a_{mn}\cdot x_n=b_m$  

Se llama **matriz de coeficientes** a:  
> M=$\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n}\\
   a_{21} & a_{22} & ... & a_{2n}\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn}\\
  \end{array} } \right)$ 
  
y matriz ampliada a:  
> M*=$\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n} & b_1\\
   a_{21} & a_{22} & ... & a_{2n} & b_2\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn} & b_3\\
  \end{array} } \right)$  

* El sistema de ecuaciones será **compatible** (tiene solución) si rangoM=rangoM*
> Compatible determinado (tiene una única solución) si rangoM=rangoM\* =n  
> Compatible indeterminado (tiene infinitas soluciones) si rangoM=rangoM* <n

* El sistema de ecuaciones será **incompatible** (no tiene solución) si rangoM≠rangoM*  



<span style="color:orange"> Ejemplo:  
Vamos a calcular si tiene solución el siguiente sistema de ecuaciones usando Python.  </style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [3]:
import numpy as np
A=np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])
detA=np.linalg.det(A)
detA

1.9999999999999998

In [4]:
import numpy as np
B=np.matrix([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
])
detB=np.linalg.det(B)
detB

LinAlgError: Last 2 dimensions of the array must be square

<span style="color:orange">Anda! No se puede....Claro! Porque el determinante sólo existe para matrices cuadradas y ésta tiene dimensión 3x4.  
¿Cómo lo hacemos?  
Tendremos que calcular hasta los 4 determinantes de orden 3 para comprobar si hay alguno diferente de 0 y el rango de B es 3.  
Eso sí, el que coincide con la matriz A no hace falta que lo calcule porque ya lo tengo calculado.  
De hecho, como el de la matriz A ya es distinto de 0, no hace falta que calcule ninguno más.  
Por tanto, el rango de B es 3 también</style>

Si el determinante de la **matriz de coeficientes** es distinto de 0, nos encontramos con un SCD.

<span style="color:orange"> Ejemplo:  
Vamos a calcular si tiene solución el siguiente sistema de ecuaciones usando Python.</style>  
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [5]:
import numpy as np
A=np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])
detA=np.linalg.det(A)
round(detA)

0.0

<span style="color:orange"> Da 0, por lo que A no tiene rango 3. Para ver si tiene rango 2, buscamos un determinante de orden 2x2 que sea diferente de 0.</style>

In [7]:
import numpy as np
A=np.matrix([
    [0,1],
    [2,-3]
])
detA=np.linalg.det(A)
round(detA)
# Sale distinto de 0

-2.0

<span style="color:orange"> Por lo que A tiene rango 2.  
¿Qué ocurre con B?  
El primer menor de orden 3, pongamos que es el de A, vale 0, por lo que tengo que probar a ver qué pasa con los otros 3</style>

In [9]:
# cogemos las columnas 2, 3 y 4
import numpy as np
B=np.matrix([
    [1,-4,8],
    [-3,2,1],
    [-8,7,1]
])
detA=np.linalg.det(B)
round(detB)

-32.0

<span style="color:orange"> Este menor de orden 3 sale distinto de 0, luego el rango de B es 3.  
Como tienen distinto rango, el sistema es incompatible, es decir, no tiene solución.</style>  

<span style="color:orange"> Ejemplo:  
Vamos a calcular si tiene solución el siguiente sistema de ecuaciones usando Python.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [10]:
# Calculamos el determinante de A
import numpy as np
A=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
detA=np.linalg.det(A)
round(detA)
# Sale 0, luego el rango de A no es 3. Probemos a ver si tiene rango 2

-0.0

In [11]:
# Vamos a coger el determinante de orden 2 formado por los primeros 4 elementos
import numpy as np
A=np.matrix([
   [1,0],
   [2,3]
])
detA=np.linalg.det(A)
round(detA)

3.0

<span style="color:orange"> Luego el rango de A es 2.  
¿Qué ocurre con B?  
El primer menor de orden 3, pongamos que es el de A, vale 0, por lo que tengo que probar a ver qué pasa con los otros 3</style>

In [12]:
import numpy as np
B=np.matrix([
    [0,1,2],
    [3,1,3],
    [3,2,5]
])
detB=np.linalg.det(B)
round(detB)

0.0

In [13]:
import numpy as np
B=np.matrix([
    [1,1,2],
    [2,1,3],
    [3,2,5]
])
detB=np.linalg.det(B)
round(detB)

0.0

In [14]:
import numpy as np
B=np.matrix([
    [1,0,2],
    [2,3,3],
    [3,3,5]
])
detB=np.linalg.det(B)
round(detB)

-0.0

<span style="color:orange"> Luego el rango de B es 2 (Bastaría con coger el mismo determinante elegido para A).  
Como coinciden y es menor que el número de incógnitas, es un SCI, es decir, tiene infinitas soluciones.</style>  

 Sabemos que hay un modo directo en Python para calcular los rangos.  
 
<span style="color:orange"> Ejemplo: Vamos a calcular el rango de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [15]:
import numpy as np
M = np.array([
    [1, -2, 1],
    [0, 2, -8],
    [-4, 5, 9]
])
M_amp = np.array([
    [1, -2, 1, 0],
    [0, 2, -8, 8],
    [-4, 5, 9, -9]
])
print("¿M y M_amp tienen el mismo rango? {}".format(np.linalg.matrix_rank(M) == np.linalg.matrix_rank(M_amp)))
print("¿El rango de M es igual a 3? {}".format(np.linalg.matrix_rank(M) == 3))
print("Por tanto el sistema es compatible determinado, es decir tienen una única solución.")

¿M y M_amp tienen el mismo rango? True
¿El rango de M es igual a 3? True
Por tanto el sistema es compatible determinado, es decir tienen una única solución.


> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [16]:
M = np.array([
    [0, 1, -4],
    [2, -3, 2],
    [5, -8, 7]
])
M_amp = np.array([
    [0, 1, -4, 8],
    [2, -3, 2, 1],
    [5, -8, 7, 1]
])
print("¿M y M_amp tienen el mismo rango? {}".format(np.linalg.matrix_rank(M) == np.linalg.matrix_rank(M_amp)))
print("El rango de M es igual a {}".format(np.linalg.matrix_rank(M)))
print("El rango de M_amp es igual a {}".format(np.linalg.matrix_rank(M_amp)))
print("Por tanto el sistema es incompatible, es decir no tiene solución.")

¿M y M_amp tienen el mismo rango? False
El rango de M es igual a 2
El rango de M_amp es igual a 3
Por tanto el sistema es incompatible, es decir no tiene solución.


> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [17]:
import numpy as np
M = np.array([
    [1, 0, 1],
    [2, 3, 1],
    [3, 3, 2]
])
M_amp = np.array([
    [1, 0, 1, 2],
    [2, 3, 1, 3],
    [3, 3, 2, 5]
])
print("¿M y M_amp tienen el mismo rango? {}".format(np.linalg.matrix_rank(M) == np.linalg.matrix_rank(M_amp)))
print("¿El rango de M es igual a 3? {}".format(np.linalg.matrix_rank(M) == 3))
print("El rango de M es igual a {}".format(np.linalg.matrix_rank(M)))
print("El rango de M_amp es igual a {}".format(np.linalg.matrix_rank(M_amp)))
print("Por tanto el sistema es compatible indeterminado, es decir tienen infinitas soluciones.")


¿M y M_amp tienen el mismo rango? True
¿El rango de M es igual a 3? False
El rango de M es igual a 2
El rango de M_amp es igual a 2
Por tanto el sistema es compatible indeterminado, es decir tienen infinitas soluciones.


## ¿Cómo calculamos la solución?  

NOTA: La conclusión al final, es que antes de calcular las soluciones, debería saber qué tipo de sistema tengo, es decir, cuántas soluciones hay, si las hay, porque los métodos no fallan, pero devuelven soluciones erróneas.  

**Método de la matriz inversa**  

Dada A $\cdot$ X = B, entonces X=A<sup>-1</sup> $\cdot$ B

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCD) usando Python y el método de la matriz inversa.  
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [21]:
import numpy as np
A=np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
   ])
B=np.matrix([
    [0],[8],[-9]
])
inv_A=np.linalg.inv(A)
inv_A*B

matrix([[29.],
        [16.],
        [ 3.]])

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SI) usando Python y el método de la matriz inversa. </style>
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [20]:
import numpy as np
A=np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
   ])
B=np.matrix([
    [8],[1],[1]
])
inv_A=np.linalg.inv(A)
inv_A*B

matrix([[-9.00719925e+15],
        [-7.20575940e+15],
        [-1.80143985e+15]])

<span style="color:orange">Sabíamos que no tenía solución y si nos fijamos los números que devuelve son enormes para el rango en que estamos trabajando, es como si fuesen "infinito".</style>

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCI) usando Python y el método de la matriz inversa.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [19]:
import numpy as np
A=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
   ])
B=np.matrix([
    [2],[3],[5]
])
inv_A=np.linalg.inv(A)
inv_A*B

matrix([[0.],
        [0.],
        [0.]])

<span style="color:orange"> En este caso me devuelve una solución "confusa", porque podría ser o no solución, y, además sabemos que tiene infinitas soluciones.  
¿Cómo haríamos para calcular todas las posibles?  
El método más general matemáticamente es la reducción gaussiana:  
$
  A=
  \left[ {\begin{array}{cc}
   1 & 0 & 1 & 2\\
   2 & 3 & 1 & 3\\
   3 & 3 & 2 & 5\\
  \end{array} } \right]
$  =  $
  \left[ {\begin{array}{cc}
   1 & 0 & 1 & 2\\
   0 & 3 & -1 & -1\\
   0 & 3 & -1 & -1\\
  \end{array} } \right]
$ = $
  \left[ {\begin{array}{cc}
   1 & 0 & 1 & 2\\
   0 & 3 & -1 & -1\\
   0 & 0 & 0 & 0\\
  \end{array} } \right]
$  
Lo que se traduce en:  </style>
><span style="color:orange"> x<sub>1</sub>+x<sub>3</sub>=2</style>  
><span style="color:orange"> 3x<sub>2</sub>-x<sub>3</sub>=-1</style>  

<span style="color:orange"> Como comparten el x<sub>3</sub>, x<sub>3</sub>=$\lambda$.  
Luego la solución queda:  
> <span style="color:orange">x<sub>1</sub> = 2-$\lambda$</style>    
> <span style="color:orange">x<sub>2</sub> = $\frac{-1+\lambda}{3}$</style>    
> <span style="color:orange">x<sub>3</sub>=$\lambda$</style>  

En Python ya vimos que hay un modo más rápido para calcular las soluciones de un sistema, en particular bastante útil cuando tiene infinitas soluciones.  

** Método "solve_linear_system" de Sympy **

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCD) usando Sympy.  
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [22]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z 

A=Matrix([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
   ])

solve_linear_system(A,x,y,z)
# Me devuelve la solución perfectamente

{x: 29, y: 16, z: 3}

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SI) usando Sympy. </style>
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [27]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z 

A=Matrix([
    [0,1,-4,8],
    [2,-3,2,1],
    [5,-8,7,1]
   ])

solve_linear_system(A,x,y,z)
# Ni siquiera devuelve nada, aunque no falla

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCI) usando Sympy.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [28]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z 

A=Matrix([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])
solve_linear_system(A,x,y,z)
# Me devuelve la solución perfectamente

{y: z/3 - 1/3, x: -z + 2}

**Método de Cramer**

Dada A $\cdot$ X = B, entonces:
* x=$\frac{A_x}{detA}$  
* y=$\frac{A_y}{detA}$  
* z=$\frac{A_z}{detA}$  

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCD) usando Python y el método de Cramer.  
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>


In [29]:
import numpy as np
A=np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
   ])
AX=np.matrix([
    [0,-2,1],
    [8,2,-8],
    [-9,5,9]
])
AY=np.matrix([
    [1,0,1],
    [0,8,-8],
    [-4,-9,9]
])
AZ=np.matrix([
    [1,-2,0],
    [0,2,8],
    [-4,5,-9]
])
x=np.linalg.det(AX)/np.linalg.det(A)
y=np.linalg.det(AY)/np.linalg.det(A)
z=np.linalg.det(AZ)/np.linalg.det(A)
X=([round(x),round(y),round(z)])
X

[29.0, 16.0, 3.0]

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SI) usando Python y el método de Cramer. </style>
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [31]:
import numpy as np
A=np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
   ])
AX=([
    [8,1,-4],
    [1,-3,2],
    [1,-8,7]
])
AY=([
    [0,8,-4],
    [2,1,2],
    [5,1,7]
])
AZ=([
    [0,1,8],
    [2,-3,1],
    [5,-8,1]
])
x=np.linalg.det(AX)/np.linalg.det(A)
y=np.linalg.det(AY)/np.linalg.det(A)
z=np.linalg.det(AZ)/np.linalg.det(A)
X=([round(x),round(y),round(z)])
X
# Como antes, me devuelve unos números terriblemente grandes, ya que no tenía solución. 
# Eso si, no falla

[-9007199254740938.0, -7205759403792747.0, -1801439850948190.0]

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCI) usando Python y el método de Cramer.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [33]:
import numpy as np
A=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
   ])
AX=np.matrix([
    [2,0,1],
    [3,3,1],
    [5,3,2]
])
AY=np.matrix([
    [1,2,1],
    [2,3,1],
    [3,5,2]
])
AZ=np.matrix([
    [1,0,2],
    [2,3,3],
    [3,3,5]
])
x=np.linalg.det(AX)/np.linalg.det(A)
y=np.linalg.det(AY)/np.linalg.det(A)
z=np.linalg.det(AZ)/np.linalg.det(A)
X=([round(x),round(y),round(z)])
X
# Devuelve una solución, pero si os fijais es errónea

[-5.0, 0.0, 3.0]

** Método de resolución de ecuaciones con Numpy**

<span style="color:orange"> Ejemplo:   
Calculemos la solución del siguiente sistema de ecuaciones (SCD) usando Numpy
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [1]:
import numpy as np

A = np.matrix(
    [[1,-2,1],
    [0,2,-8],
    [-4,5,9]]
)

B = np.matrix(
    [[0],
     [8],
     [-9]]
)

X = np.linalg.solve(A, B)
X

matrix([[29.],
        [16.],
        [ 3.]])

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SI) usando Numpy.  </style>   
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [35]:
import numpy as np

A = np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])

B = np.matrix(
    [[8],
     [1],
     [1]]
)

X = np.linalg.solve(A, B)
X
# Como podemos ver, no vale porque devuelve solución cuando no la hay.

matrix([[-9.00719925e+15],
        [-7.20575940e+15],
        [-1.80143985e+15]])

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones (SCI) usando Numpy</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [36]:
import numpy as np

A = np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])

B = np.matrix(
    [[2],
     [3],
     [5]]
)

X = np.linalg.solve(A, B)
X
# Nuevamente, solución confusa

matrix([[-0.5],
        [ 0.5],
        [ 2.5]])

<span style="color:blue"> Ejemplo: El mercado ganadero </style>   

<img src="Images/ganado.jpg" style="width: 300px;"/>

<span style="color:blue"> Tres campesinos se encontraron en el mercado ganadero.</style>  
* <span style="color:blue"> <span style="color:blue"> Mira, le dijo Luis a Juan, te daré 6 de mis cerdos por 1 de tus caballos y así tendrás el doble de animales que yo.</style>  
* <span style="color:blue"> Si ése es tu modo de hacer negocios, le dijo Pepe a Luis, te daré 14 ovejas por 1 caballo, y entonces tendrás el triple de animales que yo.</style>  
* <span style="color:blue"> Bien, le dijo Juan a Pepe. Te daré 4 vacas por un caballo y entonces tendrás seis veces más animales que yo.</style>  
<span style="color:blue"> ¿Cuántos animales llevaron al mercado Juan, Luis y Pepe?</style>  

<span style="color:blue"> Llamemos L al número de animales que tiene Luis, J al número de animales que posee Juan y P al número de animales pertenecientes a Pepe.</style>  
> <span style="color:blue">J-1+6=2·(L-6+1)</style>  
> <span style="color:blue">L-1+14=3·(P-14+1)</style>  
> <span style="color:blue">P+4-1=6·(J+1-4)</style>  
  
  
> <span style="color:blue">J-2L=-15</style>  
> <span style="color:blue">L-3P=-52</style>  
> <span style="color:blue">P-6J=-21</style> 

In [1]:
import numpy as np

A = np.matrix([
    [1,-2,0],
    [0,1,-3],
    [-6,0,1]
])

B = np.matrix(
    [[-15],
     [-52],
     [-21]]
)

X = np.linalg.solve(A, B)
X

matrix([[ 7.],
        [11.],
        [21.]])

**Método de los mínimos cuadrado** 

En el caso de que un sistema sea incompatible, podemos aproximar las soluciones utilizando el **Método de los mínimos cuadrado**

**El método de los mínimos cuadrados** nos permite resolver de forma aproximada sistemas de ecuaciones.**  

**Supongamos que tratamos de resolver un sistema de la forma Ax = b.**  

Identificando la matriz A con la matriz de una determinada aplicación lineal que la define, en una base dada, podemos entender que el sistema tiene solución siempre y cuando b ∈ Im(A). O dicho de otro modo, la columna correspondiente al segundo miembro debe ser linealmente dependiente de las columnas de la matriz A, que en esencia es lo que afirma el Teorema de Rouché-Frobenius.  

Supongamos que no existe solución para este sistema. En este caso, puede ser interesante estudiar para qué vector o vectores x', Ax' ≈ b, esto es, tratamos de buscar una solución aproximada del sistema.  

Una forma de interpretar esta aproximación es la siguiente:  
Si Ax' ≈ b, entonces podemos intentar encontrar x' tal que kAx' − bk sea lo menor posible.  
Es decir, tratamos de resolver el problema min<sub>x</sub>$\|$Ax − b $\|$  

Si el sistema tiene solución, entonces el mínimo del problema anterior es cero, y por tanto Ax = b; pero si no hay solución, tiene sentido buscar el vector x que haga menor esa norma, y por tanto que más se parece a una solución.  

Por otra parte, dado cualquier vector x, es evidente que Ax ∈ Im(A), luego el problema anterior se puede escribir como:  
min<sub>y∈Im(A)</sub>$\|$y − b $\|$b  

Al final, usando teoría de proyecciones ortogonales y algún otro concepto, se llega a la conclusión de que **se trata de resolver el sistema A<sup>T</sup>Ax'=A<sup>T</sup>b**

<span style="color:orange"> Ejemplo:  
Resolver de forma aproximada el sistema</style>  
> <span style="color:orange"> x1 + x2 + x3 = 1</style>    
> <span style="color:orange"> x1 + x2 − x3 = 1</style>  
> <span style="color:orange"> x3 = 1</style>  



In [2]:
import numpy as np
A=np.matrix([
    [1,1,1],
    [1,1,-1],
    [0,0,1]
])
B=np.matrix([
    [1],
    [1],
    [1]
])
AM=np.matrix([
    [1,1,1,1],
    [1,1,-1,1],
    [0,0,1,1]
])
rangoA=np.linalg.matrix_rank(A)
rangoA

2

In [3]:
rangoAM=np.linalg.matrix_rank(AM)
rangoAM

3

<span style="color:orange"> Luego es un sistema incompatible, por lo que no tiene solución.  
Queremos calcular AT*A*x'=AT*B  , que lo vamos a definir como: A2*x'=B2.</style>    



In [4]:
A2=np.transpose(A)*A
A2

matrix([[2, 2, 0],
        [2, 2, 0],
        [0, 0, 3]])

In [5]:
B2=np.transpose(A)*B
B2

matrix([[2],
        [2],
        [1]])

<span style="color:orange">$ \left[ {\begin{array}{cc}
   2 & 2 & 0 \\
   2 & 2 & 0 \\
   0 & 0 & 3 \\
  \end{array} } \right]
* \left[ {\begin{array}{cc}
   x_1 \\
   x_2 \\
   x_3 \\
  \end{array} } \right] = \left[ {\begin{array}{cc}
   2 \\
   2 \\
   1 \\
  \end{array} } \right]$</style>    

<span style="color:orange">x<sub>1</sub>+x<sub>2</sub>=1  
3x<sub>3</sub>=1  </style>  
  
<span style="color:orange">x<sub>2</sub>=1 -x<sub>1</sub>  
x<sub>3</sub>=$\frac{1}{3}$</style>  

<span style="color:orange">Solución: (a,1-a,$\frac{1}{3}$)</style>    

<span style="color:blue"> Ejemplo:  
Encontrar la recta que mejor aproxima a los puntos (1, 1), (2, 3), (3, 5) y (4, 6).</style>  
> <span style="color:blue">a+b=1</style>   
> <span style="color:blue">2a+b=3</style>   
> <span style="color:blue">3a+b=5</style>   
> <span style="color:blue">4a+b=6</style> 

<span style="color:blue">Ax=b.  
$A=\left[ {\begin{array}{cc}
   1 & 1 \\
   2 & 1\\
   3 & 1\\
   4 & 1\\
  \end{array} } \right]$ y $b=\left[ {\begin{array}{cc}
   1  \\
   3 \\
   5 \\
   6 \\
  \end{array} } \right]$</style>

In [6]:
import numpy as np
A=([
    [1,1],
    [2,1],
    [3,1],
    [4,1]
])
AM=([
    [1,1,1],
    [2,1,3],
    [3,1,5],
    [4,1,6]
])
np.linalg.matrix_rank(A)

2

In [7]:
import numpy as np
A=([
    [1,1],
    [2,1],
    [3,1],
    [4,1]
])
AM=([
    [1,1,1],
    [2,1,3],
    [3,1,5],
    [4,1,6]
])
np.linalg.matrix_rank(AM)

3

<span style="color:blue"> Luego es un sistema incompatible, por lo que no tiene solución.  
Queremos calcular AT*A*x'=AT*B  , que lo vamos a definir como: A2*x'=B2.</style>   

In [8]:
import numpy as np
A=np.matrix([
    [1,1],
    [2,1],
    [3,1],
    [4,1]
])
B=np.matrix([
    [1],
    [3],
    [5],
    [6]
])
A2=np.transpose(A)*A
A2

matrix([[30, 10],
        [10,  4]])

In [9]:
import numpy as np
A=np.matrix([
    [1,1],
    [2,1],
    [3,1],
    [4,1]
])
B=np.matrix([
    [1],
    [3],
    [5],
    [6]
])
B2=np.transpose(A)*B
B2

matrix([[46],
        [15]])

<span style="color:blue">$A2=\left[ {\begin{array}{cc}
   30 & 10 \\
   10 & 40\\
  \end{array} } \right]$ y $B2=\left[ {\begin{array}{cc}
   46 \\
   15 \\
  \end{array} } \right]$  </style>  
  
  > <span style="color:blue">30a+10b=46. </style>    
  > <span style="color:blue">10a+40b=15</style> 

In [10]:
np.linalg.matrix_rank(A2)

2

In [11]:
AM2=([
    [30,10,46],
    [10,40,15]
])
np.linalg.matrix_rank(AM2)

2

<span style="color:blue">Como es un SCD, la solución es muy sencilla. </style>  

In [12]:
np.linalg.solve(A2,B2)

matrix([[ 1.7],
        [-0.5]])

<span style="color:blue">Por tanto, la recta es y=1.7x-0.5 </style> 