# 11. Valores y vectores propios

# Valores y vectores propios



Un **vector propio** de una matriz A de n × n es un vector x diferente de cero tal que Ax = λx para algún escalar λ.  
Un escalar λ se llama **valor propio** de A si existe una solución no trivial x de Ax = λx.  
Una x como ésta se denomina **vector propio correspondiente a λ**.  

<span style="color:orange"> Ejemplo:  
Sean $
  A=
  \left[ {\begin{array}{cc}
   1 & 6 \\
   5 & 2 \\
  \end{array} } \right], u= \left[ {\begin{array}{cc}
   6 \\
   -5 \\
  \end{array} } \right] y  v= \left[ {\begin{array}{cc}
   3 \\
   -2 \\
  \end{array} } \right]
$. Vamos a calcular las imágenes de **u** y  **v** por **A**.</style>     

In [13]:
import numpy as np
A=np.matrix([
    [1,6],
    [5,2]
])
u=np.matrix([
    [6],
    [-5]
])
A*u
# Si nos fijamos, A*u = -4*u

matrix([[-24],
        [ 20]])

In [14]:
import numpy as np
A=np.matrix([
    [1,6],
    [5,2]
])
v=np.matrix([
    [3],
    [-2]
])
A*v

matrix([[-9],
        [11]])

<span style="color:orange"> Entonces u es un vector propio correspondiente a un valor propio (−4), pero v no es un vector propio de A porque Av no es un múltiplo de v.</style>  

<span style="color:orange"> Ejemplo:  
Demostrar que 7 es un valor propio de $
  A=
  \left[ {\begin{array}{cc}
   1 & 6 \\
   5 & 2 \\
  \end{array} } \right]$ y calcular los vectores propios correspondientes.  
  El escalar 7 es un valor propio de A si, y sólo si, la ecuación A**x**=7**x** tiene una solución no trivial. Esto es equivalente a (A-7I)**x**=**0**</style> 

In [15]:
import numpy as np
A=np.matrix([
    [1,6],
    [5,2]
])
A_7I=A-7*np.identity(2)
A_7I

matrix([[-6.,  6.],
        [ 5., -5.]])

<span style="color:orange"> Las columnas de A-7I son linealmente dependientes, así que existen soluciones no triviales, luego 7 es un valor propio de A.  
Los vectores de la forma (x<sub>2</sub>,x<sub>2</sub>) con x<sub>2</sub>≠0 son vectores propios correspondientes a λ = 7.</style>  

<span style="color:orange"> Ejemplo:  
Sea $
  A=
  \left[ {\begin{array}{cc}
   4 & -1 & 6\\
   2 & 1 & 6 \\
   2 & -1 & 8 \\
  \end{array} } \right]$. Un valor propio de A es 2. Encuentre una base para el espacio propio correspondiente.</style>  

In [1]:
import numpy as np
A=([
    [4,-1,6],
    [2,1,6],
    [2,-1,8]
])
A_2I=A-2*np.identity(3)
A_2I

array([[ 2., -1.,  6.],
       [ 2., -1.,  6.],
       [ 2., -1.,  6.]])

<span style="color:orange"> $2x_1-x_2+6x_3=0$  
$x_1$=a  
$x_3$=b  
$x_2$=2a+6b</style>   

<span style="color:orange"> {(1,0,2),(0,1,6)} base</style>  

Los valores propios de una matriz triangular son las entradas de su diagonal principal.  

<span style="color:orange"> Ejemplo:  
Sea $
  A=
  \left[ {\begin{array}{cc}
   3 & 6 & -8\\
   0 & 0 & 6 \\
   0 & 0 & 2 \\
  \end{array} } \right] y B=\left[ {\begin{array}{cc}
   4 & 0 & 0\\
   -2 & 1 & 0 \\
   5 & 3 & 4 \\
  \end{array} } \right]$.  
  Los valores propios de A son 3, 0 y 2. Los valores propios de B son 4 y 1.</style>    
  
<span style="color:orange"> Veamos ahora cómo hacerlo en Python:</style>  
  


In [7]:
import numpy as np
import scipy.linalg as la 

A = np.array([
    [3,6,-8], 
    [0, 0,6],
    [0,0,2]
])
valores_propios, autovectores_propios_en_columnas= la.eig(A)
valores_propios

array([3.+0.j, 0.+0.j, 2.+0.j])

In [8]:
autovectores_propios_en_columnas

array([[ 1.        , -0.89442719, -0.95346259],
       [ 0.        ,  0.4472136 ,  0.28603878],
       [ 0.        ,  0.        ,  0.09534626]])

¿Qué signfica que una matriz A tenga un valor propio de 0?   
0 es un valor propio de A si, y sólo si, A es no invertible.  

Si v<sub>1</sub>, ... , v<sub>r</sub> son vectores propios que corresponden a distintos valores propios λ<sub>1</sub>, ... , λ<sub>r</sub> de una matriz A de n × n, entonces el conjunto {v<sub>1</sub>, ... , v<sub>r</sub>} es linealmente independiente.  

Un escalar λ es un valor propio de una matriz A de n × n si, y sólo si, λ satisface la **ecuación característica**
> det(A−λI)=0  

Si A es una matriz de n × n, entonces det(A − λI) es un polinomio de grado n llamado **polinomio característico** de A.  

<span style="color:orange"> Ejemplo:  
Vamos a calcular la ecuación característica de $
  A=
  \left[ {\begin{array}{cc}
   5 & 2 & 6 & -1\\
   0 & 3 & -8 & 0\\
   0 & 0 & 5 & 4 \\
   0 & 0 & 0 & 1 \\
  \end{array} } \right]$. 
  detA=|A-λI|=$\left| {\begin{array}{cc}
   5-λ & 2 & 6 & -1\\
   0 & 3-λ & -8 & 0\\
   0 & 0 & 5-λ & 4 \\
   0 & 0 & 0 & 1-λ \\
  \end{array} } \right|$=(5−λ)(3−λ)(5−λ)(1−λ)=(5−λ)<sup>2</sup>(3−λ)(1−λ)  
  que es el polinomio característico.  
La ecuación característica es (5−λ)<sup>2</sup>(3−λ)(1−λ)=0</style>
  

In [8]:
import numpy as np
import sympy as sy
A=sy.Matrix([
    [5,2,6,-1],
    [0,3,-8,0],
    [0,0,5,4],
    [0,0,0,1]
])
x=sy.symbols('x')
A_xI=A-x*np.eye(4)
pol=sy.det(A_xI)
pol

1.0*x**4 - 14.0*x**3 + 68.0*x**2 - 130.0*x + 75.0

In [10]:
sy.roots(pol)
# Nos falla porque no es capaz de encontrar raices en 50 pasos, que es el maximo de roots.
# Tenemos que usar otra funcion

NoConvergence: convergence to root failed; try n < 15 or maxsteps > 50

In [17]:
# Probamos con polyroots, con el maximo numero de iteraciones que es 10.000
from mpmath import *

polyroots([1,-14,68,-130,75],10000)
# Nos saca como soluciones 1, 3 y 5 doble

[mpf('1.0'), mpf('3.0'), mpf('4.9999999987396402'), mpf('5.0000000027958365')]

<span style="color:orange">Ejemplo:  
Vamos con otro ejemplo: $
  A=
  \left[ {\begin{array}{cc}
   -1 & -4 & -3 & -2 & -1\\
   0 & -13 & -10 & -7 & -3\\
   0 & -85 & -59 & -40 & -22 \\
   0 & 104 & 74 & 50 & 27\\
   0 & 90 & 62 & 43 & 22\\
  \end{array} } \right]$. 
</style>

In [20]:
import numpy as np
import sympy as sy

A=sy.Matrix([
    [-1,-4,-3,-2,-1],
    [0,-13,-10,-7,-3],
    [0,-85,-59,-40,-22],
    [0,104,74,50,27],
    [0,90,62,43,22]
])

x=sy.symbols('x')
A_xI=A-x*np.eye(5)
pol=sy.det(A_xI)
pol

-1.0*x**5 - 1.0*x**4 + 6.0*x**3 + 14.0*x**2 + 11.0*x + 3.0

In [25]:
from mpmath import *

polyroots([-1,-1,6,14,11,3],100000)
# Parece que así no vamos a ser capaces
# Tenemos que probar otro modo

NoConvergence: Didn't converge in maxsteps=100000 steps.

In [27]:
# Probamos con eig de scipy
import scipy.linalg as la 

valores_propios, autovectores_propios_en_columnas= la.eig(A)
valores_propios
# No le gusta los objetos como los crea sympy

ValueError: object arrays are not supported

In [28]:
#Probamos a calcular la matriz A con numpy

import numpy as np
import scipy.linalg as la 

A=np.matrix([
    [-1,-4,-3,-2,-1],
    [0,-13,-10,-7,-3],
    [0,-85,-59,-40,-22],
    [0,104,74,50,27],
    [0,90,62,43,22]
])

valores_propios, autovectores_propios_en_columnas= la.eig(A)
valores_propios

array([-1.        +0.00000000e+00j,  3.        +0.00000000e+00j,
       -0.99997857+3.71197701e-05j, -0.99997857-3.71197701e-05j,
       -1.00004286+0.00000000e+00j])

In [29]:
autovectores_propios_en_columnas

array([[ 1.00000000e+00+0.00000000e+00j, -1.53264728e-16+0.00000000e+00j,
         9.99999801e-01+0.00000000e+00j,  9.99999801e-01-0.00000000e+00j,
        -9.99999801e-01+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  9.42851296e-19+0.00000000e+00j,
        -4.28596129e-05-7.42411163e-05j, -4.28596129e-05+7.42411163e-05j,
        -8.57192263e-05+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  5.77350269e-01+0.00000000e+00j,
        -1.50009105e-04-2.59843112e-04j, -1.50009105e-04+2.59843112e-04j,
        -3.00018210e-04+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j, -5.77350269e-01+0.00000000e+00j,
         2.14298065e-04+3.71205581e-04j,  2.14298065e-04-3.71205581e-04j,
         4.28596131e-04+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j, -5.77350269e-01+0.00000000e+00j,
         1.71439370e-04+2.96962874e-04j,  1.71439370e-04-2.96962874e-04j,
         3.42878742e-04+0.00000000e+00j]])

El cálculo de autovectores y autovalores tiene muchísimas aplicaciones, como puede ser el cálculo de componentes principales en Machine Learning.

Veamos un ejemplo sencillo:  es la de obtener los ejes principales de una matriz de dispersión (o de covarianza) de un conjunto de muestras. En otras palabras, ver en qué direcciones tienden a estar alineados un montón de puntos.

Un ejemplo en dos dimensiones: si calculamos la matriz de covarianza de los puntos de la figura, sus dos autovectores nos indican las direcciones marcadas por flechas, cuya longitud está dada por los autovalores. Y el autovector del mayor autovalor nos dice la dirección principal en la que se alinean los puntos.  

<img src="Images/PCA.png" style="width: 600px;"/>